"""
Static schema for the Whole Foods Market National New Item Setup Form (2018).
Field order matches the real Excel template column order (A → BI).
"""
from typing import Optional

WFM_FORM_FIELDS: list[dict] = [
    # ── Exclusivity & Launch ──────────────────────────────────────────────────
    {
        "id": "exclusivity",
        "excel_column": "A",
        "label": "Exclusivity",
        "section": "exclusivity_launch",
        "type": "text",
        "required": False,
        "source_hint": "",
        "notes": "Not in Brand Scout data; will be flagged as a gap.",
    },
    {
        "id": "manufacture_launch_month",
        "excel_column": "B",
        "label": "Manufacture Launch Month",
        "section": "exclusivity_launch",
        "type": "date",
        "required": False,
        "source_hint": "",
        "notes": "",
    },

    # ── Product Identity ──────────────────────────────────────────────────────
    {
        "id": "family",
        "excel_column": "C",
        "label": "Family",
        "section": "product_identity",
        "type": "text",
        "required": False,
        "source_hint": "",
        "notes": "Product family or line name.",
    },
    {
        "id": "category",
        "excel_column": "D",
        "label": "Category",
        "section": "product_identity",
        "type": "text",
        "required": False,
        "source_hint": "brand_evaluations.category",
        "notes": "",
    },
    {
        "id": "manufacture_upc",
        "excel_column": "E",
        "label": "Manufacture UPC",
        "section": "product_identity",
        "type": "text",
        "required": True,
        "source_hint": "",
        "notes": "12-digit UPC; not in Brand Scout data.",
    },
    {
        "id": "upc_check_digit",
        "excel_column": "F",
        "label": "UPC Check Digit",
        "section": "product_identity",
        "type": "text",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "evaluate_upc",
        "excel_column": "G",
        "label": "EVALUATE UPC",
        "section": "product_identity",
        "type": "text",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "regional_identifier_upc",
        "excel_column": "H",
        "label": "Regional Identifier UPC",
        "section": "product_identity",
        "type": "text",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "brand",
        "excel_column": "I",
        "label": "Brand",
        "section": "product_identity",
        "type": "text",
        "required": True,
        "source_hint": "brand_evaluations.brand_name",
        "notes": "",
    },
    {
        "id": "description",
        "excel_column": "J",
        "label": "Description",
        "section": "product_identity",
        "type": "text",
        "required": True,
        "source_hint": "brand_evaluations.signals_found.broker_brief",
        "notes": "From broker_brief or Scout context.",
    },
    {
        "id": "case_pack",
        "excel_column": "K",
        "label": "Case Pack",
        "section": "product_identity",
        "type": "number",
        "required": True,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "unit_size",
        "excel_column": "L",
        "label": "Unit Size",
        "section": "product_identity",
        "type": "text",
        "required": True,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "uom",
        "excel_column": "M",
        "label": "UOM",
        "section": "product_identity",
        "type": "text",
        "required": True,
        "source_hint": "",
        "notes": "Unit of measure, e.g. 'oz', 'fl oz'.",
    },

    # ── Pricing & Margin ──────────────────────────────────────────────────────
    {
        "id": "max_delivered_case_cost",
        "excel_column": "N",
        "label": "Maximum Delivered Case Cost To Distributor",
        "section": "pricing",
        "type": "currency",
        "required": True,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "max_case_cost_with_markup",
        "excel_column": "O",
        "label": "Maximum Case Cost (Including Markup)",
        "section": "pricing",
        "type": "currency",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "max_unit_cost_with_markup",
        "excel_column": "P",
        "label": "Maximum Unit Cost (Including Markup)",
        "section": "pricing",
        "type": "currency",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "srp",
        "excel_column": "Q",
        "label": "SRP",
        "section": "pricing",
        "type": "currency",
        "required": True,
        "source_hint": "brand_evaluations.extracted_fields.srp_hero",
        "notes": "Fall back to extracted_fields.srp_min if srp_hero absent.",
    },
    {
        "id": "gm_pct",
        "excel_column": "R",
        "label": "GM%",
        "section": "pricing",
        "type": "number",
        "required": False,
        "source_hint": "",
        "notes": "",
    },

    # ── Distributor ───────────────────────────────────────────────────────────
    {
        "id": "distributor_name",
        "excel_column": "S",
        "label": "Distributor (or vendor name if shipping direct)",
        "section": "distributor",
        "type": "text",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "distributor_vin",
        "excel_column": "T",
        "label": "VIN - Vendor Item #",
        "section": "distributor",
        "type": "text",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "distributor_cost_effective_date",
        "excel_column": "U",
        "label": "Cost Effective Date",
        "section": "distributor",
        "type": "date",
        "required": False,
        "source_hint": "",
        "notes": "",
    },

    # ── UNFI East ─────────────────────────────────────────────────────────────
    {
        "id": "unfi_east_item_code",
        "excel_column": "V",
        "label": "UNFI East Item Code",
        "section": "unfi_east",
        "type": "text",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "unfi_east_case_cost",
        "excel_column": "W",
        "label": "UNFI East Case Cost",
        "section": "unfi_east",
        "type": "currency",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "unfi_east_cost_effective_date",
        "excel_column": "X",
        "label": "UNFI East Cost Effective Date",
        "section": "unfi_east",
        "type": "date",
        "required": False,
        "source_hint": "",
        "notes": "",
    },

    # ── UNFI West ─────────────────────────────────────────────────────────────
    {
        "id": "unfi_west_item_code",
        "excel_column": "Y",
        "label": "UNFI West Item Code",
        "section": "unfi_west",
        "type": "text",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "unfi_west_lancaster_sw_cost",
        "excel_column": "Z",
        "label": "Lancaster (SW) Cost",
        "section": "unfi_west",
        "type": "currency",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "unfi_west_denver_rm_cost",
        "excel_column": "AA",
        "label": "Denver (RM) Cost",
        "section": "unfi_west",
        "type": "currency",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "unfi_west_rocklin_nc_cost",
        "excel_column": "AB",
        "label": "Rocklin (NC) Cost",
        "section": "unfi_west",
        "type": "currency",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "unfi_west_mor_vall_sc_cost",
        "excel_column": "AC",
        "label": "Mor Vall (SC) Cost",
        "section": "unfi_west",
        "type": "currency",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "unfi_west_rdg_aub_pnw_cost",
        "excel_column": "AD",
        "label": "Rdg/Aub (PNW) Cost",
        "section": "unfi_west",
        "type": "currency",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "unfi_west_cost_effective_date",
        "excel_column": "AE",
        "label": "UNFI West Cost Effective Date",
        "section": "unfi_west",
        "type": "date",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "promotional_support_summary",
        "excel_column": "AF",
        "label": "Promotional Support Program Summary",
        "section": "unfi_west",
        "type": "text",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "demo_support",
        "excel_column": "AG",
        "label": "Demo Support Program (# Stores / Frequency)",
        "section": "unfi_west",
        "type": "text",
        "required": False,
        "source_hint": "",
        "notes": "",
    },

    # ── Attributes (Certifications) ───────────────────────────────────────────
    {
        "id": "usda_organic",
        "excel_column": "AH",
        "label": "USDA Organic (Y/N)",
        "section": "attributes",
        "type": "yes_no",
        "required": False,
        "source_hint": "brand_evaluations.extracted_fields.certifications",
        "notes": "",
    },
    {
        "id": "non_gmo_verified",
        "excel_column": "AI",
        "label": "Non-GMO Project Verified (Y/N)",
        "section": "attributes",
        "type": "yes_no",
        "required": False,
        "source_hint": "brand_evaluations.extracted_fields.certifications",
        "notes": "",
    },
    {
        "id": "demeter_biodynamic",
        "excel_column": "AJ",
        "label": "Demeter (Biodynamic) Certified (Y/N)",
        "section": "attributes",
        "type": "yes_no",
        "required": False,
        "source_hint": "brand_evaluations.extracted_fields.certifications",
        "notes": "",
    },
    {
        "id": "fair_trade",
        "excel_column": "AK",
        "label": "Fair Trade Certified (Y/N)",
        "section": "attributes",
        "type": "yes_no",
        "required": False,
        "source_hint": "brand_evaluations.extracted_fields.certifications",
        "notes": "",
    },
    {
        "id": "third_party_gluten_free",
        "excel_column": "AL",
        "label": "Third Party Gluten Free Cert (Y/N)",
        "section": "attributes",
        "type": "yes_no",
        "required": False,
        "source_hint": "brand_evaluations.extracted_fields.certifications",
        "notes": "",
    },
    {
        "id": "ecoscale_audit",
        "excel_column": "AM",
        "label": "EcoScale Audit (cleaning only)",
        "section": "attributes",
        "type": "yes_no",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "is_line_extension",
        "excel_column": "AN",
        "label": "Is this item a Line Extension",
        "section": "attributes",
        "type": "yes_no",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "like_item_upc",
        "excel_column": "AO",
        "label": "Like Item UPC (if line extension)",
        "section": "attributes",
        "type": "text",
        "required": False,
        "source_hint": "",
        "notes": "",
    },

    # ── Space Planning (Dimensions) ───────────────────────────────────────────
    {
        "id": "height",
        "excel_column": "AP",
        "label": "Height",
        "section": "space_planning",
        "type": "dimensions",
        "required": False,
        "source_hint": "",
        "notes": "In inches.",
    },
    {
        "id": "width",
        "excel_column": "AQ",
        "label": "Width",
        "section": "space_planning",
        "type": "dimensions",
        "required": False,
        "source_hint": "",
        "notes": "In inches.",
    },
    {
        "id": "depth",
        "excel_column": "AR",
        "label": "Depth",
        "section": "space_planning",
        "type": "dimensions",
        "required": False,
        "source_hint": "",
        "notes": "In inches.",
    },
    {
        "id": "merchandised_in_tray",
        "excel_column": "AS",
        "label": "Merchandised In Tray?",
        "section": "space_planning",
        "type": "yes_no",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "units_per_tray",
        "excel_column": "AT",
        "label": "Units Per Tray",
        "section": "space_planning",
        "type": "number",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "tray_height",
        "excel_column": "AU",
        "label": "Tray Height",
        "section": "space_planning",
        "type": "dimensions",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "tray_width",
        "excel_column": "AV",
        "label": "Tray Width",
        "section": "space_planning",
        "type": "dimensions",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "tray_depth",
        "excel_column": "AW",
        "label": "Tray Depth",
        "section": "space_planning",
        "type": "dimensions",
        "required": False,
        "source_hint": "",
        "notes": "",
    },

    # ── Pallet Configuration ──────────────────────────────────────────────────
    {
        "id": "cases_per_pallet",
        "excel_column": "AX",
        "label": "Cases per pallet",
        "section": "pallet_config",
        "type": "number",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "pallet_tie",
        "excel_column": "AY",
        "label": "Pallet Tie (cases per layer)",
        "section": "pallet_config",
        "type": "number",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "pallet_high",
        "excel_column": "AZ",
        "label": "Pallet High (layers per pallet)",
        "section": "pallet_config",
        "type": "number",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "case_dimensions",
        "excel_column": "BA",
        "label": "Case Dimensions (LxWxH)",
        "section": "pallet_config",
        "type": "text",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "case_cube",
        "excel_column": "BB",
        "label": "CASE CUBE",
        "section": "pallet_config",
        "type": "number",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "case_weight_lbs",
        "excel_column": "BC",
        "label": "CASE WEIGHT (LBs.)",
        "section": "pallet_config",
        "type": "number",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "pallet_weight_lbs",
        "excel_column": "BD",
        "label": "PALLET WEIGHT (LBs.)",
        "section": "pallet_config",
        "type": "number",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
    {
        "id": "pallets_per_truckload",
        "excel_column": "BE",
        "label": "Pallets per Truckload",
        "section": "pallet_config",
        "type": "number",
        "required": False,
        "source_hint": "",
        "notes": "",
    },

    # ── Vendor Contact ────────────────────────────────────────────────────────
    {
        "id": "manufacturer_company",
        "excel_column": "BF",
        "label": "Manufacturer / Company",
        "section": "vendor_contact",
        "type": "text",
        "required": True,
        "source_hint": "brand_evaluations.brand_name",
        "notes": "Use brand_name for DTC brands.",
    },
    {
        "id": "vendor_contact_name",
        "excel_column": "BG",
        "label": "Vendor Contact Name",
        "section": "vendor_contact",
        "type": "text",
        "required": True,
        "source_hint": "brand_evaluations.founder_name",
        "notes": "",
    },
    {
        "id": "vendor_contact_email",
        "excel_column": "BH",
        "label": "Vendor Contact Email",
        "section": "vendor_contact",
        "type": "text",
        "required": True,
        "source_hint": "brand_evaluations.founder_email",
        "notes": "",
    },
    {
        "id": "vendor_contact_phone",
        "excel_column": "BI",
        "label": "Vendor Contact Phone",
        "section": "vendor_contact",
        "type": "text",
        "required": False,
        "source_hint": "",
        "notes": "",
    },
]

FIELD_SECTIONS = {
    "exclusivity_launch": "Exclusivity & Launch",
    "product_identity":   "Product Identity",
    "pricing":            "Pricing & Margin",
    "distributor":        "Distributor",
    "unfi_east":          "UNFI East",
    "unfi_west":          "UNFI West",
    "attributes":         "Attributes (Certifications)",
    "space_planning":     "Space Planning (Dimensions)",
    "pallet_config":      "Pallet Configuration",
    "vendor_contact":     "Vendor Contact",
}


def get_fields_by_section(section_id: str) -> list[dict]:
    return [f for f in WFM_FORM_FIELDS if f["section"] == section_id]


def get_field(field_id: str) -> Optional[dict]:
    return next((f for f in WFM_FORM_FIELDS if f["id"] == field_id), None)
