"""Queue view — the default landing page after 'I'm a broker'.

Renders the stack of cards inside the shared broker shell. Cards collapse /
expand inline. All actions (Approve & send, Send, Skip) are visual only
for v1 — they update session-state counters that the sidebar reads.
"""
from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

import streamlit as st


def _esc(s: str) -> str:
    """Escape characters Streamlit's markdown parser steals from us:
    $ (LaTeX delimiter)."""
    return s.replace("$", "&#36;")


# Display labels for agent_origin / Drafted-by attribution.
_AGENT_LABELS = {
    "retailer_pitcher": "Retailer Pitcher",
    "brand_scout":      "Brand Scout",
    "new_item_forms":   "New Item Forms",
}


# Inline phrases we linkify into a clickable doc reference.
# (regex pattern → doc_type to open)
_LINKIFY_PATTERNS: list[tuple[str, str]] = [
    (r"\bsell sheet \+ cost build attached\b",  "sell_sheet"),
    (r"\bsell sheet attached\b",                "sell_sheet"),
    (r"\brenewal sheet attached\b",             "sell_sheet"),
    (r"\bone-pager\b",                          "one_pager"),
    (r"\bUNFI new-item forms? filled\b",        "new_item_form"),
    (r"\bKeHE new-item forms? drafted\b",       "new_item_form"),
    (r"\bnew-item forms? filled and ready\b",   "new_item_form"),
    (r"\bform drafted\b",                       "new_item_form"),
]


def _linkify_doc_refs(text: str, card_id: str, available_doc_types: set[str]) -> str:
    """Wrap inline doc-reference phrases in <a class="bf-doc-link">.
    Only links to doc types the card actually produces.

    Uses data-doc-id (not href URL navigation) so the JS panel handler
    opens the panel instantly without a Streamlit rerun."""
    import re
    out = text
    for pattern, doc_type in _LINKIFY_PATTERNS:
        if doc_type not in available_doc_types:
            continue
        doc_id = f"{card_id}:{doc_type}"
        out = re.sub(
            pattern,
            (lambda m, d=doc_id: f'<a class="bf-doc-link" href="#" '
                                 f'data-doc-id="{d}">{m.group(0)}</a>'),
            out,
            count=1,
            flags=re.IGNORECASE,
        )
    return out



def _render_all_doc_panels() -> None:
    """Pre-render every card's doc previews as hidden HTML blocks plus
    a dim overlay. JS toggles them on/off — clicking an attachment is
    pure CSS, no Streamlit rerun, no re-render of the queue.

    PDFs are filename-predictable so the "Open as PDF" / "Download"
    links work as soon as the background-thread PDF generator finishes
    (kicked off at the top of render_queue_view)."""
    from agents._shared import document_data as _dd
    from ui import doc_preview as _dp

    panels: list[str] = []
    for card in SEED_CARDS:
        if not card.docs:
            continue
        agent_label = "BrokerFlow"
        if card.agent_origin:
            agent_label = _AGENT_LABELS.get(card.agent_origin[0], "BrokerFlow")

        for doc_type, _label in card.docs:
            payload = _dd.get_payload(card.id, doc_type)
            if not payload:
                continue
            eyebrow, title, subtitle, body_html = _dp.render_preview_body(
                doc_type, payload,
            )
            doc_id = f"{card.id}:{doc_type}"
            pdf_url = f"/app/static/agent_docs/{card.id}_{doc_type}.pdf"
            subtitle_html = (
                f'<div class="bf-doc-subtitle">{subtitle}</div>'
                if subtitle else ""
            )
            panels.append(
                f'<aside class="bf-doc-panel-html" data-doc-id="{doc_id}">'
                '<div class="bf-doc-head">'
                '<div class="bf-doc-head-text">'
                f'<div class="bf-doc-eyebrow">{eyebrow}</div>'
                f'<div class="bf-doc-title">{title}</div>'
                f'{subtitle_html}'
                '</div>'
                '<div class="bf-doc-actions">'
                f'<a class="bf-doc-action" href="{pdf_url}" target="_blank">'
                '&#8599; Open as PDF</a>'
                f'<a class="bf-doc-action" href="{pdf_url}" '
                'download target="_blank">&darr; Download</a>'
                '<a class="bf-doc-action bf-doc-action--close '
                'bf-doc-close-btn" href="#">&times;</a>'
                '</div>'
                '</div>'
                f'<div class="bf-doc-preview-body">{body_html}</div>'
                '<div class="bf-doc-foot">'
                f'<span>Generated by {agent_label} &middot; just now</span>'
                '<a class="bf-doc-foot-regen" href="#">Regenerate</a>'
                '</div>'
                '</aside>'
            )

    # Inject preview CSS + the overlay + every panel in ONE markdown
    # block so all the panels and the overlay render as siblings
    # children of the same stMarkdownContainer in the DOM.
    st.markdown(
        _dp.PREVIEW_CSS
        + '<div class="bf-doc-overlay-html"></div>'
        + "".join(panels),
        unsafe_allow_html=True,
    )


# ── Seed data ────────────────────────────────────────────────────────────────

@dataclass
class ReasoningBullet:
    text: str
    source: str  # "LEDGER" | "EVENTS" | "INBOX" | ""


@dataclass
class Card:
    id: str
    type: str            # Topic tag: "PITCH" | "RENEWAL" | "NEW BRAND" | "NEW ITEM"
    needs_you: bool
    context: str         # "Costco NW · Marcus"
    elapsed: str         # "2m"
    summary_html: str    # 1-2 sentences with <b>...</b> bolded numbers
    primary_action: str  # button label
    skip_label: str = "Skip"
    brand: str = ""      # filter key (matches sidebar BROKER_BRANDS)

    # Agent attribution — list of agent keys that produced this card. Used by
    # the WHY block "Drafted by:" line and by PDF generation. Order matters
    # (e.g. NEW BRAND credits Brand Scout → Retailer Pitcher).
    agent_origin: list[str] = field(default_factory=list)
    # Documents this card produces. Each is a (doc_type, label) tuple matching
    # pdf_generator template keys: "sell_sheet" | "one_pager" | "new_item_form"
    # | "cost_build". Side panel resolves the URL via doc_storage.
    docs: list[tuple[str, str]] = field(default_factory=list)

    # Expanded view
    from_email: str = ""
    from_body: str = ""
    drafted_to: str = ""
    drafted_subject: str = ""
    drafted_body: str = ""
    drafted_label: str = "DRAFTED REPLY"  # or "DRAFTED ACTION"
    reasoning: list[ReasoningBullet] = field(default_factory=list)


SEED_CARDS: list[Card] = [
    Card(
        id="card-1",
        type="PITCH",
        needs_you=True,
        context="Costco NW · Marcus",
        elapsed="2m",
        summary_html=(
            "Drafted pitch for <b>Brami</b> to Costco NW. Lupini snacks "
            "indexing <b>3.1×</b> on Faire in PNW + clean promo "
            "independence. Sell sheet attached, proposing <b>142-store "
            "rollout</b> pegged to May reset."
        ),
        primary_action="Approve & send",
        brand="Brami",
        agent_origin=["retailer_pitcher"],
        docs=[("sell_sheet", "Sell sheet"), ("cost_build", "Cost build")],
        drafted_label="DRAFTED PITCH",
        drafted_to="marcus.alvarez@costco.com",
        drafted_subject="Brami × Costco NW — May reset, 142 stores",
        drafted_body=(
            "Hi Marcus,\n\n"
            "Bringing Brami to you for the May reset. Lupini bean snacks "
            "are indexing 3.1× on Faire across the PNW over the last 90 "
            "days, with no promo dependency in the velocity curve — "
            "rare for the category.\n\n"
            "Proposing the full 142-store NW footprint, sea salt + "
            "garlic SKUs, $1.99 intro for the first 6 weeks. Margin "
            "structure holds at 32% retailer margin even with the "
            "intro pricing.\n\n"
            "Sell sheet + cost build attached. Happy to walk through "
            "anytime this week — the May reset window closes 5/14.\n\n"
            "— Nadia"
        ),
        reasoning=[
            ReasoningBullet(
                "Faire 90-day velocity: 3.1× category baseline in PNW",
                "EVENTS",
            ),
            ReasoningBullet(
                "Promo independence score: 0.91 (clean — velocity holds without TPRs)",
                "EVENTS",
            ),
            ReasoningBullet(
                "Costco NW open SKU slots: 142 stores, 2 SKU max per brand",
                "LEDGER",
            ),
            ReasoningBullet(
                "Marcus's May reset deadline: 5/14 (locked window)",
                "INBOX",
            ),
            ReasoningBullet(
                "Margin model: $1.99 intro → 32% retailer margin (passes Costco threshold)",
                "",
            ),
            ReasoningBullet(
                "Marcus accepted 4 of last 6 pitches Nadia ran with this structure",
                "INBOX",
            ),
        ],
    ),
    Card(
        id="card-2",
        type="NEW BRAND",
        needs_you=True,
        context="Faire signal",
        elapsed="4h",
        summary_html=(
            "Found a new <b>sparkling tea brand</b> trending <b>4.2×</b> "
            "on Faire and Instacart with clean promo independence. "
            "Scored <b>87/100 — Broker Ready</b>. Drafted intro email "
            "and one-pager for your next outbound batch."
        ),
        primary_action="Review verdict",
        brand="",
        agent_origin=["brand_scout", "retailer_pitcher"],
        docs=[("one_pager", "Brand one-pager")],
        drafted_label="DRAFTED ACTION",
        drafted_to="founders@steepsparkling.co",
        drafted_subject="Steep Sparkling × Nadia — quick intro",
        drafted_body=(
            "Hey team,\n\n"
            "Came across Steep Sparkling on Faire — your Q1 trajectory "
            "is in the top 5% of beverage SKUs we track, with clean "
            "promo independence and the velocity story holding up "
            "across Faire and Instacart.\n\n"
            "I work with a handful of brands in your category and would "
            "love 15 minutes to see whether broker representation makes "
            "sense for where you're going next quarter.\n\n"
            "— Nadia"
        ),
        reasoning=[
            ReasoningBullet(
                "Velocity proof: 22/25 — top 5% Faire beverage, 4.2× category baseline",
                "EVENTS",
            ),
            ReasoningBullet(
                "Distribution density: 16/20 — Faire + Instacart + 11 indie shops",
                "EVENTS",
            ),
            ReasoningBullet(
                "Margin viability: 14/20 — 38% retailer margin holds at SRP $4.99",
                "",
            ),
            ReasoningBullet(
                "Brand story clarity: 18/20 — single-origin sourcing + functional claim",
                "",
            ),
            ReasoningBullet(
                "Promo independence: 17/15 (capped) — 0.94 score, no TPR dependency",
                "EVENTS",
            ),
            ReasoningBullet(
                "Composite: 87/100 — Broker Ready (45–69 = ready, 70+ = established)",
                "",
            ),
            ReasoningBullet(
                "Broker representation gap: no broker of record in CA / NW yet",
                "EVENTS",
            ),
        ],
    ),
    Card(
        id="card-3",
        type="NEW ITEM",
        needs_you=False,
        context="Whole Foods · Olipop",
        elapsed="12m",
        summary_html=(
            "Whole Foods accepted <b>6 new SKUs</b> for Olipop. UNFI "
            "new-item forms filled and ready. <b>4 fields need "
            "confirmation</b>. <b>1 cert expires in 31 days</b>."
        ),
        primary_action="Review fields",
        brand="Olipop",
        agent_origin=["new_item_forms"],
        docs=[("new_item_form", "UNFI new-item form")],
        drafted_label="FORMS DRAFTED",
        drafted_to="UNFI new-item portal — Olipop, 6 SKUs",
        drafted_subject="Olipop · Whole Foods · 6 SKUs · UNFI form package",
        drafted_body=(
            "Form package ready for review:\n\n"
            "  • Olipop Strawberry Vanilla 12oz — auto-filled (38/38 fields)\n"
            "  • Olipop Vintage Cola 12oz — auto-filled (38/38 fields)\n"
            "  • Olipop Cherry Vanilla 12oz — auto-filled (38/38 fields)\n"
            "  • Olipop Orange Cream 12oz — auto-filled (38/38 fields)\n"
            "  • Olipop Banana Cream 12oz — needs confirmation (4 fields)\n"
            "  • Olipop Doctor Goodwin 12oz — auto-filled (38/38 fields)\n\n"
            "Outstanding on Banana Cream:\n"
            "  • Case pack dimensions (carton L×W×H)\n"
            "  • Pallet ti/hi configuration\n"
            "  • Slotting fee acceptance ($1,200/SKU)\n"
            "  • FOB origin confirmation\n\n"
            "⚠ Organic certificate on file expires 6/5 — request renewal "
            "from brand before submitting package."
        ),
        reasoning=[
            ReasoningBullet(
                "Whole Foods accepted 6 SKUs in 4/29 category review meeting",
                "EVENTS",
            ),
            ReasoningBullet(
                "UNFI new-item template v3.2 (current as of 4/15)",
                "LEDGER",
            ),
            ReasoningBullet(
                "Olipop canonical record: 32 of 38 fields complete per SKU",
                "LEDGER",
            ),
            ReasoningBullet(
                "Banana Cream missing 4 fields — newest SKU, packaging not yet finalized",
                "LEDGER",
            ),
            ReasoningBullet(
                "Organic cert on file: USDA #1247-A, expires 2026-06-05 (31 days)",
                "LEDGER",
            ),
            ReasoningBullet(
                "Whole Foods set fee window opens 5/12 — 7 days to package + submit",
                "EVENTS",
            ),
        ],
    ),
    Card(
        id="card-4",
        type="RENEWAL",
        needs_you=False,
        context="Sprouts · Danielle",
        elapsed="3h",
        summary_html=(
            "Drafted FY27 renewal pitch for <b>Spudsy</b> at same "
            "<b>$126/pallet</b> rate as FY26. Sprouts BA volume up "
            "<b>18% YoY</b> — flagging room to push for higher rate at "
            "next review."
        ),
        primary_action="Approve & send",
        brand="Spudsy",
        agent_origin=["retailer_pitcher"],
        docs=[("sell_sheet", "Renewal sheet")],
        drafted_label="DRAFTED PITCH",
        drafted_to="danielle.ortiz@sprouts.com",
        drafted_subject="Spudsy FY27 renewal — Sprouts BA",
        drafted_body=(
            "Hi Danielle,\n\n"
            "Holding the Spudsy pallet rate at $126 for FY27 in the BA "
            "region — same as FY26. Spudsy BA volume is up 18% YoY so "
            "we're comfortable carrying the rate flat into next year.\n\n"
            "Quick note: with the volume trajectory we're seeing, the "
            "next category review (Q3) is probably the right window to "
            "revisit pricing — happy to bring data when we get there.\n\n"
            "Send the agreement and we'll countersign same week.\n\n"
            "— Nadia"
        ),
        reasoning=[
            ReasoningBullet("FY26 BA pallet rate: $126/pallet", "LEDGER"),
            ReasoningBullet(
                "Spudsy BA YoY pallet volume growth: +18% (rolling 12mo)",
                "EVENTS",
            ),
            ReasoningBullet(
                "Comparable region (NW Spudsy) renewed at $134 last quarter",
                "EVENTS",
            ),
            ReasoningBullet(
                "Sprouts Q3 category review window: 7/14–7/28 (next pricing lever)",
                "EVENTS",
            ),
            ReasoningBullet(
                "Danielle's avg renewal-cycle response time: 2 days",
                "INBOX",
            ),
        ],
    ),
    Card(
        id="card-5",
        type="NEW BRAND",
        needs_you=False,
        context="Instacart signal",
        elapsed="1h",
        summary_html=(
            "Tracked a new <b>functional snack brand</b> spiking "
            "<b>6×</b> on Instacart over 30 days. Scored "
            "<b>72/100 — Worth a Look</b>. Margins thin but velocity "
            "exceptional. Drafted summary for your review."
        ),
        primary_action="Review verdict",
        brand="",
        agent_origin=["brand_scout", "retailer_pitcher"],
        docs=[("one_pager", "Brand one-pager")],
        drafted_label="DRAFTED SUMMARY",
        drafted_to="Internal — Brand Scout note · Stride Bites",
        drafted_subject="Stride Bites — high velocity, thin margin",
        drafted_body=(
            "New brand surfaced via Instacart 30-day spike monitor:\n\n"
            "Stride Bites — functional protein cookies, hitting 6× "
            "category baseline on Instacart over the last 30 days. "
            "Velocity story is exceptional but margin profile is "
            "tight: 24% retailer margin at SRP $5.49, below the 28% "
            "threshold most of your retailers want.\n\n"
            "Verdict: Worth a Look (72/100). Recommend a 15-min call "
            "with the brand before pitching — if they have flexibility "
            "to land at $5.99 SRP, the margin clears and velocity story "
            "carries the rest.\n\n"
            "Want me to draft an intro email?"
        ),
        reasoning=[
            ReasoningBullet(
                "Velocity proof: 24/25 — 6× Instacart category baseline (30-day)",
                "EVENTS",
            ),
            ReasoningBullet(
                "Distribution density: 11/20 — Instacart + DTC only, no shelf yet",
                "EVENTS",
            ),
            ReasoningBullet(
                "Margin viability: 9/20 — 24% retailer margin (below 28% threshold)",
                "",
            ),
            ReasoningBullet(
                "Brand story clarity: 16/20 — clear functional claim, weak founder narrative",
                "",
            ),
            ReasoningBullet(
                "Promo independence: 12/15 — slight TPR dependency in week-over-week curve",
                "EVENTS",
            ),
            ReasoningBullet(
                "Composite: 72/100 — Worth a Look (margin gap is the swing factor)",
                "",
            ),
        ],
    ),
    Card(
        id="card-6",
        type="NEW ITEM",
        needs_you=False,
        context="KeHE · Tia Lupita",
        elapsed="6h",
        summary_html=(
            "KeHE new-item form for <b>Tia Lupita salsa</b> drafted. "
            "<b>38 of 42 fields</b> auto-filled from canonical brand "
            "record. Outstanding: case pack dimensions, slotting fee "
            "acceptance, FOB origin, broker code."
        ),
        primary_action="Review fields",
        brand="Tia Lupita",
        agent_origin=["new_item_forms"],
        docs=[("new_item_form", "KeHE new-item form")],
        drafted_label="FORM DRAFTED",
        drafted_to="KeHE new-item portal — Tia Lupita salsa verde 16oz",
        drafted_subject="Tia Lupita · KeHE · salsa verde 16oz · 38/42 filled",
        drafted_body=(
            "KeHE form draft ready (template v4.1, current):\n\n"
            "Auto-filled from canonical record (38 fields):\n"
            "  • Brand identity, contact, certs, cost build, retail margin\n"
            "  • Nutrition panel, allergen flags, ingredient deck\n"
            "  • UPC/GTIN, SCC, country of origin, gross/net weight\n\n"
            "Outstanding (4 fields — need brand confirmation):\n"
            "  • Case pack dimensions (carton L×W×H, gross weight)\n"
            "  • Slotting fee acceptance ($800/SKU per KeHE schedule)\n"
            "  • FOB origin (port of entry vs. domestic copacker)\n"
            "  • Broker code assignment (Nadia: BR-NA-0241)\n\n"
            "Submit window: KeHE Q2 set fee opens 5/19, closes 5/30."
        ),
        reasoning=[
            ReasoningBullet(
                "KeHE new-item template v4.1 — refreshed 4/22",
                "LEDGER",
            ),
            ReasoningBullet(
                "Tia Lupita canonical record: 38 of 42 KeHE-required fields complete",
                "LEDGER",
            ),
            ReasoningBullet(
                "Missing fields are co-packer dependent — last refresh 11mo ago",
                "LEDGER",
            ),
            ReasoningBullet(
                "KeHE Q2 set fee window: 5/19–5/30 (next submission opportunity)",
                "EVENTS",
            ),
            ReasoningBullet(
                "Slotting fee schedule: $800/SKU (KeHE Q2 rate card)",
                "LEDGER",
            ),
        ],
    ),
]


# ── Filtering ────────────────────────────────────────────────────────────────

def _filter_cards(filter_key: str, brand: Optional[str]) -> list[Card]:
    sent = st.session_state.get("queue_sent_ids", set())
    skipped = st.session_state.get("queue_skipped_ids", set())

    if filter_key == "sent":
        return [c for c in SEED_CARDS if c.id in sent]
    if filter_key == "skipped":
        return [c for c in SEED_CARDS if c.id in skipped]

    cards = [c for c in SEED_CARDS if c.id not in sent and c.id not in skipped]

    if filter_key == "needs_you":
        cards = [c for c in cards if c.needs_you]
    if filter_key == "drafted":
        cards = [c for c in cards if not c.needs_you]
    if brand:
        cards = [c for c in cards if c.brand == brand]
    return cards


def _filter_label(filter_key: str, brand: Optional[str]) -> str:
    if brand:
        return brand
    return {
        "today":     "Today",
        "needs_you": "Needs you",
        "drafted":   "Drafted",
        "sent":      "Sent",
        "skipped":   "Skipped",
    }.get(filter_key, "Today")


# ── Page-scoped CSS ──────────────────────────────────────────────────────────

_QUEUE_CSS = """
<style>
/* ── Ask BrokerFlow bar — full-width pill styled st.text_input ──── */
div[data-testid="stLayoutWrapper"]:has(.bf-ask-marker) {
    border: none !important;
    background: transparent !important;
    padding: 0 !important;
    margin: 0 0 14px !important;
    box-shadow: none !important;
    position: relative;
}
div[data-testid="stLayoutWrapper"]:has(.bf-ask-marker) > div[data-testid="stVerticalBlock"] {
    border: none !important;
    padding: 0 !important;
    background: transparent !important;
    box-shadow: none !important;
    gap: 0 !important;
}
div[data-testid="stLayoutWrapper"]:has(.bf-ask-marker) .stTextInput input {
    width: 100% !important;
    background: #FFFFFF !important;
    border: 1px solid #EAEAE4 !important;
    border-radius: 999px !important;
    padding: 14px 70px 14px 22px !important;
    font-family: 'Inter', sans-serif !important;
    font-size: 14px !important;
    color: #1A1A18 !important;
    box-shadow: none !important;
}
div[data-testid="stLayoutWrapper"]:has(.bf-ask-marker) .stTextInput input::placeholder {
    color: #A8A8A8 !important;
    -webkit-text-fill-color: #A8A8A8 !important;
}
div[data-testid="stLayoutWrapper"]:has(.bf-ask-marker) .stTextInput input:focus {
    border-color: #1A1A18 !important;
    outline: none !important;
}
div[data-testid="stLayoutWrapper"]:has(.bf-ask-marker)::after {
    content: "⌘K";
    position: absolute;
    right: 22px;
    top: 50%;
    transform: translateY(-50%);
    font-family: 'JetBrains Mono', 'SF Mono', monospace;
    font-size: 11px;
    color: #8B8A83;
    background: #F2F2EE;
    padding: 4px 9px;
    border-radius: 6px;
    pointer-events: none;
    z-index: 1;
}

/* ── Drafted-by line (in WHY block) ─────────────────────────────── */
.bf-drafted-by {
    font-family: 'Inter', sans-serif;
    font-size: 12px;
    color: #8B8A83;
    margin: -2px 0 12px;
}
.bf-drafted-by-agent {
    color: #1A1A18;
    font-weight: 500;
}
.bf-drafted-by-time {
    color: #B0AFA8;
}

/* ── Inline attached-doc reference ──────────────────────────────── */
.bf-doc-link,
.bf-doc-link:link,
.bf-doc-link:visited {
    color: #B07A1C;
    text-decoration: underline;
    text-decoration-color: #E8A33D;
    text-underline-offset: 2px;
    font-weight: 500;
    cursor: pointer;
    text-decoration-thickness: 1px;
}
.bf-doc-link:hover {
    color: #8E5E10;
    text-decoration-color: #1A1A18;
}
.bf-doc-link::after {
    content: " ↗";
    font-size: 10px;
    color: #B07A1C;
}

/* ── Attachments row (in expanded card, above action buttons) ──── */
.bf-attach-row {
    border-top: 1px solid #F2F2EE;
    padding: 16px 0 12px;
    margin-top: 18px;
}
.bf-attach-h {
    font-family: 'Inter', sans-serif;
    font-size: 10.5px;
    font-weight: 600;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: #8B8A83;
    margin-bottom: 10px;
}
.bf-attach-item,
.bf-attach-item:link,
.bf-attach-item:visited {
    display: flex;
    align-items: center;
    gap: 14px;
    padding: 8px 0;
    text-decoration: none;
    border-top: 1px solid #F2F2EE;
}
.bf-attach-item:first-of-type { border-top: none; }
.bf-attach-item:hover .bf-attach-name { color: #1A1A18; }
.bf-attach-icon {
    font-family: 'Inter', sans-serif;
    font-size: 14px;
    color: #8B8A83;
    width: 22px;
    text-align: center;
}
.bf-attach-name {
    font-family: 'Inter', sans-serif;
    font-size: 13.5px;
    color: #57564F;
    flex: 1;
}
.bf-attach-meta {
    font-family: 'JetBrains Mono', monospace;
    font-size: 11px;
    color: #B0AFA8;
    margin-right: 14px;
}
.bf-attach-open {
    font-family: 'Inter', sans-serif;
    font-size: 12px;
    font-weight: 500;
    color: #B07A1C;
    letter-spacing: 0.02em;
}

/* ── Document side panel (slides in from right) — pure HTML, no
   Streamlit container required since panels are pre-rendered hidden
   and toggled via JS. */
@keyframes bf-fade-in {
    from { opacity: 0; }
    to { opacity: 1; }
}
@keyframes bf-doc-slide {
    from { transform: translateX(40px); opacity: 0.4; }
    to   { transform: translateX(0); opacity: 1; }
}

.bf-doc-overlay-html {
    position: fixed;
    inset: 0;
    background: rgba(10, 10, 10, 0.22);
    z-index: 250;
    display: none;
}
.bf-doc-overlay-html.open {
    display: block;
    animation: bf-fade-in 0.18s ease-out;
}

.bf-doc-panel-html {
    position: fixed;
    top: 0;
    right: 0;
    bottom: 0;
    width: 540px;
    height: 100vh;
    background: #FAFAF7;
    border-left: 1px solid #EAEAE4;
    box-shadow: -16px 0 40px -8px rgba(10, 10, 10, 0.18);
    z-index: 260;
    display: none;
    flex-direction: column;
    overflow: hidden;
}
.bf-doc-panel-html.open {
    display: flex;
    animation: bf-doc-slide 0.22s ease-out;
}
@media (max-width: 820px) {
    .bf-doc-panel-html { width: 100vw; }
}

.bf-doc-head {
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    gap: 14px;
    padding: 22px 26px 18px;
    border-bottom: 1px solid #EAEAE4;
    background: #FAFAF7;
}
.bf-doc-head-text {
    flex: 1;
    min-width: 0;
}
.bf-doc-eyebrow {
    font-family: 'Inter', sans-serif;
    font-size: 10.5px;
    font-weight: 600;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: #B0AFA8;
    margin-bottom: 6px;
}
.bf-doc-title {
    font-family: 'Instrument Serif', Georgia, serif;
    font-size: 22px;
    line-height: 1.2;
    color: #1A1A18;
    margin: 0;
}
.bf-doc-subtitle {
    font-family: 'Instrument Serif', Georgia, serif;
    font-style: italic;
    font-size: 13.5px;
    color: #8B8A83;
    margin-top: 4px;
}
.bf-doc-actions {
    display: flex;
    gap: 14px;
    align-items: center;
    flex-shrink: 0;
}
.bf-doc-action,
.bf-doc-action:link,
.bf-doc-action:visited {
    font-family: 'Inter', sans-serif;
    font-size: 12px;
    color: #57564F;
    text-decoration: none;
    padding: 6px 10px;
    border-radius: 6px;
    transition: background 0.12s ease;
    white-space: nowrap;
}
.bf-doc-action:hover { background: #F2F2EE; color: #1A1A18; }
.bf-doc-action--close {
    font-size: 18px;
    line-height: 1;
    padding: 4px 10px;
    color: #8B8A83;
}
/* Legacy iframe body — kept as fallback if a doc_type has no preview
   template yet. Native HTML preview lives in .bf-doc-preview-body. */
.bf-doc-body {
    flex: 1 1 auto;
    overflow: hidden;
    background: #1A1A18;
}
.bf-doc-body iframe {
    width: 100%;
    height: 100%;
    border: 0;
    background: #1A1A18;
}
.bf-doc-foot {
    flex: 0 0 auto;
    border-top: 1px solid #EAEAE4;
    padding: 12px 26px 16px;
    display: flex;
    justify-content: space-between;
    align-items: center;
    font-family: 'Inter', sans-serif;
    font-size: 11.5px;
    color: #8B8A83;
}
.bf-doc-foot-regen,
.bf-doc-foot-regen:link {
    color: #8B8A83;
    text-decoration: none;
}
.bf-doc-foot-regen:hover { color: #1A1A18; text-decoration: underline; }

/* ── Slide-up chat panel ────────────────────────────────────────── */
/* Dim backdrop sitting behind the chat panel. Click closes the chat. */
.bf-chat-backdrop {
    position: fixed;
    top: 0;
    left: 240px;
    right: 0;
    bottom: 0;
    background: rgba(10, 10, 10, 0.18);
    z-index: 190;
    animation: bf-fade-in 0.18s ease-out;
}
@media (max-width: 820px) {
    .bf-chat-backdrop { left: 0; }
}

/* Streamlit container holding .bf-chat-marker becomes a fixed bottom panel.
   :has() scopes the absolute styling without leaking onto other pages.
   Width is explicit (calc) so right:0 doesn't get ignored when the
   inner stLayoutWrapper is already 100% wide in normal flow. */
div[data-testid="stLayoutWrapper"]:has(.bf-chat-marker) {
    position: fixed !important;
    left: 240px !important;
    right: 0 !important;
    bottom: 80px !important;          /* leave room for fixed input bar */
    width: calc(100vw - 240px) !important;
    height: calc(70vh - 80px) !important;
    background: #FAFAF7 !important;
    border-top: 1px solid #EAEAE4 !important;
    border-left: none !important;
    border-right: none !important;
    border-bottom: none !important;
    border-radius: 16px 16px 0 0 !important;
    box-shadow: 0 -16px 40px -16px rgba(10, 10, 10, 0.12) !important;
    padding: 0 !important;
    margin: 0 !important;
    z-index: 200 !important;
    overflow: hidden !important;
    animation: bf-chat-slide 0.22s ease-out;
}
div[data-testid="stLayoutWrapper"]:has(.bf-chat-marker) > div[data-testid="stVerticalBlock"] {
    border: none !important;
    background: transparent !important;
    padding: 24px 36px 24px !important;
    height: 100% !important;
    display: flex !important;
    flex-direction: column !important;
    gap: 0 !important;
    overflow: hidden !important;
}
@keyframes bf-chat-slide {
    from { transform: translateY(20px); opacity: 0.6; }
    to   { transform: translateY(0); opacity: 1; }
}
@media (max-width: 820px) {
    div[data-testid="stLayoutWrapper"]:has(.bf-chat-marker) {
        left: 0 !important;
        height: 88vh !important;
    }
}

/* Chat panel header */
.bf-chat-head {
    display: flex;
    align-items: center;
    justify-content: space-between;
    padding-bottom: 12px;
    border-bottom: 1px solid #F2F2EE;
}
.bf-chat-head-l {
    display: flex;
    align-items: center;
    gap: 16px;
}
.bf-chat-newchat,
.bf-chat-newchat:link,
.bf-chat-newchat:visited {
    font-family: 'Inter', sans-serif;
    font-size: 12px;
    color: #57564F;
    text-decoration: none;
    display: inline-flex;
    align-items: center;
    gap: 6px;
}
.bf-chat-newchat:hover { color: #1A1A18; }
.bf-chat-newchat-plus {
    display: inline-flex;
    align-items: center;
    justify-content: center;
    width: 18px; height: 18px;
    border: 1px solid #D6D6D2;
    border-radius: 50%;
    font-size: 12px;
    line-height: 1;
    color: #57564F;
}
.bf-chat-close,
.bf-chat-close:link,
.bf-chat-close:visited {
    font-family: 'Inter', sans-serif;
    font-size: 18px;
    color: #8B8A83;
    text-decoration: none;
    line-height: 1;
    padding: 4px 8px;
    border-radius: 6px;
    transition: background 0.12s ease;
}
.bf-chat-close:hover { background: #F2F2EE; color: #1A1A18; }
.bf-chat-sub {
    font-family: 'Instrument Serif', Georgia, serif;
    font-style: italic;
    font-size: 14px;
    color: #8B8A83;
    margin: 10px 0 18px;
}

/* Chat messages area — flex-grows to fill remaining space, scrolls */
div[data-testid="stLayoutWrapper"]:has(.bf-chat-marker) .bf-chat-msgs-marker {
    display: none;
}
.bf-chat-msg-user {
    align-self: flex-end;
    max-width: 75%;
    background: #1A1A18;
    color: #FAFAF7;
    border-radius: 18px 18px 4px 18px;
    padding: 10px 16px;
    font-family: 'Inter', sans-serif;
    font-size: 14px;
    line-height: 1.5;
    margin: 6px 0 14px auto;
    width: fit-content;
}
.bf-chat-msg-assistant {
    font-family: 'Instrument Serif', Georgia, serif;
    font-size: 16px;
    line-height: 1.5;
    color: #1A1A18;
    margin: 4px 0 16px;
    max-width: 92%;
}
/* Tight spacing — match a scannable note, not a double-spaced doc */
.bf-chat-msg-assistant p {
    font-family: 'Instrument Serif', Georgia, serif !important;
    font-size: inherit !important;
    color: inherit !important;
    line-height: 1.5 !important;
    margin: 0 0 10px !important;
}
.bf-chat-msg-assistant p:last-child { margin-bottom: 0 !important; }
.bf-chat-msg-assistant strong,
.bf-chat-msg-assistant b {
    font-family: 'Instrument Serif', Georgia, serif !important;
    font-weight: 600 !important;
    color: #1A1A18 !important;
}
.bf-chat-msg-assistant ul,
.bf-chat-msg-assistant ol {
    margin: 6px 0 10px !important;
    padding-left: 22px !important;
}
.bf-chat-msg-assistant li {
    font-family: 'Instrument Serif', Georgia, serif !important;
    font-size: inherit !important;
    line-height: 1.5 !important;
    color: #1A1A18 !important;
    margin: 2px 0 !important;
}
.bf-chat-msg-assistant li > p { margin: 0 !important; }
.bf-chat-msg-assistant h1,
.bf-chat-msg-assistant h2,
.bf-chat-msg-assistant h3 {
    font-family: 'Instrument Serif', Georgia, serif !important;
    margin: 14px 0 6px !important;
    line-height: 1.3 !important;
}

@keyframes bf-chat-cursor {
    0%, 49%   { opacity: 1; }
    50%, 100% { opacity: 0; }
}
.bf-chat-cursor {
    display: inline-block;
    width: 2px;
    height: 1em;
    background: #1A1A18;
    margin-left: 2px;
    vertical-align: text-bottom;
    animation: bf-chat-cursor 1s step-end infinite;
}

/* Scrollable conversation area inside the panel.
   Streamlit-managed container (st.container) gets the marker so the
   :has() selector applies — open/close raw HTML divs don't actually
   wrap subsequent stMarkdown blocks in the DOM, so a real container
   is the only way to make a real flex/overflow region. */
.bf-chat-msgs-marker { display: none; }

div[data-testid="stLayoutWrapper"]:has(.bf-chat-marker) div[data-testid="stLayoutWrapper"]:has(.bf-chat-msgs-marker) {
    flex: 1 1 auto !important;
    min-height: 0 !important;
    overflow-y: auto !important;
    overflow-x: hidden !important;
    padding: 4px 0 24px !important;
    margin: 0 !important;
    background: transparent !important;
    border: none !important;
    border-radius: 0 !important;
    box-shadow: none !important;
    /* Smooth scroll for the auto-scroll-to-bottom */
    scroll-behavior: smooth;
}
div[data-testid="stLayoutWrapper"]:has(.bf-chat-marker) div[data-testid="stLayoutWrapper"]:has(.bf-chat-msgs-marker) > div[data-testid="stVerticalBlock"] {
    border: none !important;
    background: transparent !important;
    padding: 0 !important;
    gap: 0 !important;
}
div[data-testid="stLayoutWrapper"]:has(.bf-chat-marker) div[data-testid="stLayoutWrapper"]:has(.bf-chat-msgs-marker)::-webkit-scrollbar {
    width: 6px;
}
div[data-testid="stLayoutWrapper"]:has(.bf-chat-marker) div[data-testid="stLayoutWrapper"]:has(.bf-chat-msgs-marker)::-webkit-scrollbar-thumb {
    background: #EAEAE4;
    border-radius: 99px;
}
div[data-testid="stLayoutWrapper"]:has(.bf-chat-marker) div[data-testid="stLayoutWrapper"]:has(.bf-chat-msgs-marker)::-webkit-scrollbar-track {
    background: transparent;
}

/* Footer input bar — fixed to viewport bottom, just above the panel's
   content area. Sits on top of the panel (same z stack) but pinned. */
div[data-testid="stLayoutWrapper"]:has(.bf-chat-input-marker) {
    position: fixed !important;
    left: 240px !important;
    right: 0 !important;
    bottom: 0 !important;
    width: calc(100vw - 240px) !important;
    height: 80px !important;
    background: #FAFAF7 !important;
    border: none !important;
    border-top: 1px solid #EAEAE4 !important;
    padding: 16px 36px !important;
    margin: 0 !important;
    box-shadow: 0 -4px 16px -8px rgba(10, 10, 10, 0.08) !important;
    border-radius: 0 !important;
    z-index: 201 !important;
    display: flex !important;
    align-items: center !important;
}
div[data-testid="stLayoutWrapper"]:has(.bf-chat-input-marker) > div[data-testid="stVerticalBlock"] {
    border: none !important;
    padding: 0 !important;
    background: transparent !important;
    gap: 0 !important;
}
div[data-testid="stLayoutWrapper"]:has(.bf-chat-input-marker) .stTextInput input {
    width: 100% !important;
    background: #FFFFFF !important;
    border: 1px solid #EAEAE4 !important;
    border-radius: 999px !important;
    padding: 12px 90px 12px 20px !important;
    font-family: 'Inter', sans-serif !important;
    font-size: 14px !important;
    color: #1A1A18 !important;
    box-shadow: none !important;
}
div[data-testid="stLayoutWrapper"]:has(.bf-chat-input-marker) .stTextInput input:focus {
    border-color: #1A1A18 !important;
    outline: none !important;
}
div[data-testid="stLayoutWrapper"]:has(.bf-chat-input-marker)::after {
    content: "Send  ↵";
    position: absolute;
    right: 26px;
    top: 50%;
    transform: translateY(-50%);
    font-family: 'Inter', sans-serif;
    font-size: 12px;
    font-weight: 500;
    color: #1A1A18;
    background: #E8A33D;
    padding: 6px 12px;
    border-radius: 999px;
    pointer-events: none;
    z-index: 1;
    letter-spacing: 0.02em;
}

/* st.form chrome inside the chat input — strip border + padding so
   the pill input is the only visible chrome. The form_submit_button
   stays rendered (Enter submits) but is visually hidden — the CSS
   ::after Send pill above is the user-facing affordance. */
div[data-testid="stLayoutWrapper"]:has(.bf-chat-input-marker)
  div[data-testid="stForm"] {
    border: none !important;
    padding: 0 !important;
    background: transparent !important;
    width: 100% !important;
}
div[data-testid="stLayoutWrapper"]:has(.bf-chat-input-marker)
  div[data-testid="stFormSubmitButton"] {
    position: absolute !important;
    width: 1px !important;
    height: 1px !important;
    overflow: hidden !important;
    clip: rect(0, 0, 0, 0) !important;
    pointer-events: none !important;
    opacity: 0 !important;
}

.bf-queue-section-row {
    display: flex;
    align-items: center;
    justify-content: space-between;
    margin: 6px 0 16px;
}
.bf-queue-h {
    font-family: 'Inter', sans-serif;
    font-size: 13px;
    font-weight: 600;
    color: #1A1A18;
    letter-spacing: 0;
    margin: 0;
    text-transform: none;
}
.bf-queue-h-count { color: #B0AFA8; font-weight: 400; }

/* ── One-row topbar (breadcrumb left + ask bar right) ──────────── */
.bf-queue-topbar-marker { display: none; }

/* The Streamlit st.columns row that holds breadcrumb + ask bar */
div[data-testid="stHorizontalBlock"]:has(.bf-queue-topbar-marker) {
    align-items: center !important;
    margin-bottom: 4px !important;
    padding-bottom: 18px !important;
    border-bottom: 1px solid #F2F2EE !important;
    gap: 24px !important;
}
/* Breadcrumb cell — vertically centered with the input */
div[data-testid="stHorizontalBlock"]:has(.bf-queue-topbar-marker)
  > div[data-testid="stColumn"]:first-child {
    display: flex;
    align-items: center;
    min-height: 0 !important;
}
/* Ask input cell — pill style, right-aligned, capped width */
div[data-testid="stHorizontalBlock"]:has(.bf-queue-topbar-marker)
  > div[data-testid="stColumn"]:last-child {
    display: flex !important;
    justify-content: flex-end !important;
    position: relative !important;
}
div[data-testid="stHorizontalBlock"]:has(.bf-queue-topbar-marker)
  .stTextInput {
    max-width: 480px;
    width: 100%;
}
div[data-testid="stHorizontalBlock"]:has(.bf-queue-topbar-marker)
  .stTextInput input {
    width: 100% !important;
    background: #FFFFFF !important;
    border: 1px solid #EAEAE4 !important;
    border-radius: 999px !important;
    padding: 10px 60px 10px 18px !important;
    font-family: 'Inter', sans-serif !important;
    font-size: 13.5px !important;
    color: #1A1A18 !important;
    box-shadow: none !important;
}
div[data-testid="stHorizontalBlock"]:has(.bf-queue-topbar-marker)
  .stTextInput input::placeholder {
    color: #A8A8A8 !important;
    -webkit-text-fill-color: #A8A8A8 !important;
}
div[data-testid="stHorizontalBlock"]:has(.bf-queue-topbar-marker)
  .stTextInput input:focus {
    border-color: #1A1A18 !important;
    outline: none !important;
}
div[data-testid="stHorizontalBlock"]:has(.bf-queue-topbar-marker)
  > div[data-testid="stColumn"]:last-child::after {
    content: "⌘K";
    position: absolute;
    right: 18px;
    top: 22px;
    font-family: 'JetBrains Mono', 'SF Mono', monospace;
    font-size: 10.5px;
    color: #8B8A83;
    background: #F2F2EE;
    padding: 3px 8px;
    border-radius: 5px;
    pointer-events: none;
}

/* st.form wrapper inside the topbar — kill its border + padding so
   the input pill stays the only visible chrome */
div[data-testid="stHorizontalBlock"]:has(.bf-queue-topbar-marker)
  div[data-testid="stForm"] {
    border: none !important;
    padding: 0 !important;
    background: transparent !important;
    width: 100%;
    max-width: 480px;
    position: relative;
}
/* Hide the form_submit_button — Enter on the input still submits the
   form. The ⌘K hint above is the visual affordance. */
div[data-testid="stHorizontalBlock"]:has(.bf-queue-topbar-marker)
  div[data-testid="stFormSubmitButton"] {
    position: absolute !important;
    width: 1px !important;
    height: 1px !important;
    overflow: hidden !important;
    clip: rect(0, 0, 0, 0) !important;
    pointer-events: none !important;
    opacity: 0 !important;
}
/* Streamlit's "Press Enter to submit form" hint that pops in next to
   the input on focus — overlaps our placeholder. Suppress it
   throughout the queue (we only have form inputs whose Enter
   behavior is already obvious). */
div[data-testid="InputInstructions"],
[data-testid="stFormSubmitInstructions"] {
    display: none !important;
    visibility: hidden !important;
    width: 0 !important;
    height: 0 !important;
}

.bf-queue-pills {
    display: flex;
    gap: 8px;
}
.bf-queue-pill,
.bf-queue-pill:link,
.bf-queue-pill:visited {
    font-family: 'Inter', sans-serif;
    font-size: 11.5px;
    font-weight: 500;
    letter-spacing: 0.04em;
    padding: 6px 12px;
    border-radius: 999px;
    border: 1px solid #EAEAE4;
    color: #57564F;
    background: transparent;
    text-decoration: none;
    text-transform: uppercase;
    transition: all 0.12s ease;
}
.bf-queue-pill:hover { border-color: #1A1A18; color: #1A1A18; }
.bf-queue-pill--active {
    background: #1A1A18 !important;
    color: #FAFAF7 !important;
    border-color: #1A1A18 !important;
}

/* ── Card (uses Streamlit st.container(border=True) wrapper) ──────────
   Streamlit renders bordered containers as
   div[data-testid="stVerticalBlockBorderWrapper"]. We use vertical-block
   adjacency to scope the border styling to the queue. Each card's
   contents include a hidden marker that flips expanded styling. */
div[data-testid="stLayoutWrapper"]:has(.bf-card-marker) {
    background: #FAFAF7 !important;
    border: 1px solid #EAEAE4 !important;
    border-radius: 10px !important;
    padding: 18px 20px !important;
    margin: 0 0 14px !important;
    transition: border-color 0.12s ease !important;
    box-shadow: none !important;
}
div[data-testid="stLayoutWrapper"]:has(.bf-card-marker):hover {
    border-color: #D6D6D2 !important;
}
div[data-testid="stLayoutWrapper"]:has(.bf-card-marker--expanded) {
    border-color: #1A1A18 !important;
    background: #FFFFFF !important;
}
/* Strip Streamlit's inner stVerticalBlock border + padding inside our cards */
div[data-testid="stLayoutWrapper"]:has(.bf-card-marker) > div[data-testid="stVerticalBlock"] {
    border: none !important;
    padding: 0 !important;
    background: transparent !important;
    box-shadow: none !important;
}

.bf-card-top {
    display: flex;
    align-items: flex-start;
    justify-content: space-between;
    gap: 16px;
    margin-bottom: 10px;
}
/* New header-row layout: tag/context left + inline actions right.
   Streamlit places these inside an stHorizontalBlock; the card marker
   scopes the styling.

   Key alignment rules:
   - Tag pills are min-width so PITCH/NEW BRAND/NEW ITEM/RENEWAL all
     occupy the same horizontal slot.
   - NEEDS YOU is always in the DOM; cards without it render an
     invisible placeholder so context starts at the same x.
   - Action group columns are fixed-pixel via flex-basis so every
     Skip/Edit/primary right-edge lines up across all cards.
   - All header-row flex children align-items: center → vertical
     baseline matches across tags, context, time, and buttons.
   - 48px min-height makes cards visually rhyme regardless of which
     buttons they contain. */

.bf-card-header-l {
    display: flex;
    align-items: center;
    gap: 8px;
    flex-wrap: nowrap;
    min-height: 32px;
}
.bf-card-time-cell {
    display: flex;
    align-items: center;
    justify-content: flex-end;
    height: 100%;
    min-height: 32px;
    width: 100%;
}

/* Outer header row (left content + right action group) */
div[data-testid="stLayoutWrapper"]:has(.bf-card-marker)
  > div[data-testid="stVerticalBlock"]
  > div[data-testid="stHorizontalBlock"]:first-of-type {
    gap: 12px !important;
    align-items: center !important;
    margin-bottom: 8px !important;
    min-height: 48px !important;
}

/* Inner action row (time + primary + edit + skip) — gap 12px, right-
   aligned, vertically centered. */
div[data-testid="stLayoutWrapper"]:has(.bf-card-marker)
  div[data-testid="stHorizontalBlock"]
  div[data-testid="stHorizontalBlock"] {
    gap: 12px !important;
    align-items: center !important;
    justify-content: flex-end !important;
    flex-wrap: nowrap !important;
}

/* Pixel-pin each action column. Streamlit columns use flex; we
   override basis + max-width so widths are absolute. */
div[data-testid="stLayoutWrapper"]:has(.bf-card-marker)
  div[data-testid="stHorizontalBlock"]
  div[data-testid="stHorizontalBlock"]
  > div[data-testid="stColumn"]:nth-child(1) {
    flex: 0 0 48px !important;
    max-width: 48px !important;
    min-width: 48px !important;
    width: 48px !important;
}
div[data-testid="stLayoutWrapper"]:has(.bf-card-marker)
  div[data-testid="stHorizontalBlock"]
  div[data-testid="stHorizontalBlock"]
  > div[data-testid="stColumn"]:nth-child(2) {
    flex: 0 0 160px !important;
    max-width: 160px !important;
    min-width: 160px !important;
    width: 160px !important;
}
div[data-testid="stLayoutWrapper"]:has(.bf-card-marker)
  div[data-testid="stHorizontalBlock"]
  div[data-testid="stHorizontalBlock"]
  > div[data-testid="stColumn"]:nth-child(3) {
    flex: 0 0 80px !important;
    max-width: 80px !important;
    min-width: 80px !important;
    width: 80px !important;
}
div[data-testid="stLayoutWrapper"]:has(.bf-card-marker)
  div[data-testid="stHorizontalBlock"]
  div[data-testid="stHorizontalBlock"]
  > div[data-testid="stColumn"]:nth-child(4) {
    flex: 0 0 60px !important;
    max-width: 60px !important;
    min-width: 60px !important;
    width: 60px !important;
}
.bf-tagrow {
    display: flex;
    align-items: center;
    gap: 8px;
    flex-wrap: wrap;
}
.bf-tag {
    font-family: 'Inter', sans-serif;
    font-size: 10.5px;
    font-weight: 600;
    letter-spacing: 0.08em;
    text-transform: uppercase;
    color: #1A1A18;
    background: #F2F2EE;
    padding: 5px 8px;
    border-radius: 4px;
    display: inline-flex;
    align-items: center;
    justify-content: center;
    box-sizing: border-box;
    flex-shrink: 0;
    line-height: 1;
    white-space: nowrap;
}
/* Topic tag (PITCH / RENEWAL / NEW BRAND / NEW ITEM) — exact width
   so the NEEDS YOU slot starts at the same x on every card,
   regardless of tag text length. NEW BRAND is the longest at ~80px
   text + 20px padding ≈ 100px, so 110 gives a small buffer. */
.bf-tag.bf-tag--type {
    width: 110px;
    min-width: 110px;
    max-width: 110px;
}
.bf-tag--needs {
    background: #FBE9E7;
    color: #B23A22;
    width: 100px;
    min-width: 100px;
    max-width: 100px;
}
/* Reserve the NEEDS YOU slot even when the card doesn't need
   attention — keeps the context text x-position consistent. */
.bf-tag--needs-placeholder {
    visibility: hidden;
}
.bf-context {
    font-family: 'Inter', sans-serif;
    font-size: 12.5px;
    color: #8B8A83;
    line-height: 1.2;
    flex-shrink: 1;
    min-width: 0;
}
.bf-elapsed {
    font-family: 'JetBrains Mono', monospace;
    font-size: 11.5px;
    color: #B0AFA8;
    line-height: 1.2;
}

.bf-card-summary {
    font-family: 'Inter', sans-serif;
    font-size: 14.5px;
    line-height: 1.55;
    color: #1A1A18;
    margin: 0 0 4px;
}
.bf-card-summary b { font-weight: 600; color: #1A1A18; }

/* ── Native <details> expand — no Streamlit rerun, instant ─────── */
.bf-card-details {
    margin-top: 0;
}
.bf-card-details > summary.bf-card-summary-row {
    list-style: none;
    cursor: pointer;
    display: flex;
    flex-direction: column;
    gap: 4px;
    padding: 0;
}
.bf-card-details > summary.bf-card-summary-row::-webkit-details-marker { display: none; }

.bf-show-reasoning {
    font-family: 'Inter', sans-serif;
    font-size: 12px;
    color: #8B8A83;
    text-decoration: none;
    display: inline-flex;
    align-items: center;
    gap: 4px;
    margin-top: 2px;
}
.bf-card-details:hover .bf-show-reasoning { color: #1A1A18; }
.bf-card-details[open] .bf-show-reasoning { color: #1A1A18; }
.bf-card-details[open] .bf-show-reasoning .bf-chevron {
    transform: rotate(180deg);
    display: inline-block;
}
.bf-card-details:not([open]) .bf-show-reasoning .bf-chevron {
    display: inline-block;
}

/* Active-card visual: blue accent on summary, darker border on the
   parent card container */
div[data-testid="stLayoutWrapper"]:has(.bf-card-details[open]) {
    border-color: #1A1A18 !important;
    background: #FFFFFF !important;
}
.bf-card-details[open] > summary.bf-card-summary-row .bf-card-summary {
    border-left: 3px solid #2D5F8A;
    padding-left: 14px;
    margin: 6px 0 16px;
}

/* Extras wrapper — gets a soft top divider so it visually separates
   from the always-visible summary */
.bf-card-extras {
    margin-top: 14px;
    padding-top: 14px;
    border-top: 1px solid #F2F2EE;
}

/* Edit-mode summary gets the same blue accent as the open <details>
   summary so the active card is visually obvious. */
.bf-card-summary--editing {
    border-left: 3px solid #2D5F8A;
    padding-left: 14px;
    margin: 6px 0 16px;
}

/* Read-only subject label above the editable body */
.bf-edit-subject {
    display: flex;
    align-items: baseline;
    gap: 10px;
    padding: 10px 16px;
    background: #FAFAF7;
    border: 1px solid #EAEAE4;
    border-radius: 8px 8px 0 0;
    border-bottom: none;
    font-family: 'Inter', sans-serif;
    font-size: 13.5px;
    color: #1A1A18;
    margin-bottom: 0;
}
.bf-edit-subject-label {
    font-size: 10.5px;
    font-weight: 600;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: #8B8A83;
    flex-shrink: 0;
}
.bf-edit-subject-value {
    font-weight: 500;
}

/* Style the Streamlit textarea inside the edit-mode card to feel
   continuous with the subject row above it. */
div[data-testid="stLayoutWrapper"]:has(.bf-card-edit-mode)
  .stTextArea textarea {
    background: #FFFFFF !important;
    border: 1px solid #EAEAE4 !important;
    border-top: none !important;
    border-radius: 0 0 8px 8px !important;
    padding: 16px !important;
    font-family: 'Inter', sans-serif !important;
    font-size: 14px !important;
    line-height: 1.6 !important;
    color: #1A1A18 !important;
    box-shadow: none !important;
    margin-bottom: 14px !important;
    min-height: 240px !important;
}
div[data-testid="stLayoutWrapper"]:has(.bf-card-edit-mode)
  .stTextArea textarea:focus {
    border-color: #1A1A18 !important;
    border-top: none !important;
    outline: none !important;
}

/* Expanded blocks */
.bf-block-h {
    font-family: 'Inter', sans-serif;
    font-size: 10.5px;
    font-weight: 600;
    letter-spacing: 0.12em;
    text-transform: uppercase;
    color: #8B8A83;
    margin: 22px 0 8px;
}
.bf-from {
    background: #F4F4EF;
    border: 1px solid #EAEAE4;
    border-radius: 8px;
    padding: 14px 16px;
    font-family: 'Inter', sans-serif;
    font-size: 13.5px;
    color: #57564F;
    line-height: 1.55;
    white-space: pre-wrap;
}
.bf-draft-wrap {
    border: 1px solid #EAEAE4;
    border-radius: 8px;
    background: #FFFFFF;
    overflow: hidden;
}
.bf-draft-subject {
    font-family: 'Inter', sans-serif;
    font-size: 13.5px;
    font-weight: 600;
    color: #1A1A18;
    background: #FAFAF7;
    border-bottom: 1px solid #EAEAE4;
    padding: 10px 16px;
}
.bf-draft-body {
    font-family: 'Inter', sans-serif;
    font-size: 14px;
    color: #1A1A18;
    line-height: 1.6;
    padding: 16px;
    white-space: pre-wrap;
}

.bf-reasoning {
    list-style: none;
    padding: 0;
    margin: 0;
}
.bf-reasoning li {
    display: flex;
    justify-content: space-between;
    gap: 16px;
    padding: 8px 0;
    border-bottom: 1px solid #F2F2EE;
    font-family: 'Inter', sans-serif;
    font-size: 13px;
    color: #1A1A18;
}
.bf-reasoning li:last-child { border-bottom: none; }
.bf-reasoning .bf-reason-text { line-height: 1.55; }
.bf-reasoning .bf-reason-text u {
    text-decoration: underline;
    text-decoration-color: #D6D6D2;
    text-underline-offset: 2px;
}
.bf-reason-src {
    font-family: 'JetBrains Mono', monospace;
    font-size: 10.5px;
    color: #8B8A83;
    letter-spacing: 0.06em;
    white-space: nowrap;
    flex-shrink: 0;
    margin-top: 2px;
}

/* Queue action buttons — scoped to bordered card containers via :has().
   Streamlit's data-testid is "stButton" with no key suffix, so we use
   button[kind=primary|secondary|tertiary] instead. */
div[data-testid="stLayoutWrapper"]:has(.bf-card-marker) div[data-testid="stButton"] > button {
    font-family: 'Inter', sans-serif !important;
    font-size: 11.5px !important;
    font-weight: 500 !important;
    border-radius: 999px !important;
    padding: 4px 12px !important;
    min-height: 28px !important;
    line-height: 1.2 !important;
    box-shadow: none !important;
    transition: all 0.12s ease !important;
    white-space: nowrap !important;
}

/* Primary (Approve & send / Send / Draft / Review) — mustard pill */
div[data-testid="stLayoutWrapper"]:has(.bf-card-marker) div[data-testid="stButton"] > button[kind="primary"] {
    background: #E8A33D !important;
    background-color: #E8A33D !important;
    color: #1A1A18 !important;
    -webkit-text-fill-color: #1A1A18 !important;
    border: 1px solid #E8A33D !important;
}
div[data-testid="stLayoutWrapper"]:has(.bf-card-marker) div[data-testid="stButton"] > button[kind="primary"] p,
div[data-testid="stLayoutWrapper"]:has(.bf-card-marker) div[data-testid="stButton"] > button[kind="primary"] span {
    color: #1A1A18 !important;
    -webkit-text-fill-color: #1A1A18 !important;
}
div[data-testid="stLayoutWrapper"]:has(.bf-card-marker) div[data-testid="stButton"] > button[kind="primary"]:hover {
    background: #D89530 !important;
    background-color: #D89530 !important;
    border-color: #D89530 !important;
}

/* Secondary (Edit) — outlined ghost */
div[data-testid="stLayoutWrapper"]:has(.bf-card-marker) div[data-testid="stButton"] > button[kind="secondary"] {
    background: transparent !important;
    background-color: transparent !important;
    color: #57564F !important;
    -webkit-text-fill-color: #57564F !important;
    border: 1px solid #D6D6D2 !important;
}
div[data-testid="stLayoutWrapper"]:has(.bf-card-marker) div[data-testid="stButton"] > button[kind="secondary"] p,
div[data-testid="stLayoutWrapper"]:has(.bf-card-marker) div[data-testid="stButton"] > button[kind="secondary"] span {
    color: #57564F !important;
    -webkit-text-fill-color: #57564F !important;
}
div[data-testid="stLayoutWrapper"]:has(.bf-card-marker) div[data-testid="stButton"] > button[kind="secondary"]:hover {
    background: #F2F2EE !important;
    background-color: #F2F2EE !important;
    border-color: #1A1A18 !important;
    color: #1A1A18 !important;
    -webkit-text-fill-color: #1A1A18 !important;
}

/* Tertiary (Skip) — text-only muted */
div[data-testid="stLayoutWrapper"]:has(.bf-card-marker) div[data-testid="stButton"] > button[kind="tertiary"] {
    background: transparent !important;
    background-color: transparent !important;
    color: #8B8A83 !important;
    -webkit-text-fill-color: #8B8A83 !important;
    border: 1px solid transparent !important;
}
div[data-testid="stLayoutWrapper"]:has(.bf-card-marker) div[data-testid="stButton"] > button[kind="tertiary"] p,
div[data-testid="stLayoutWrapper"]:has(.bf-card-marker) div[data-testid="stButton"] > button[kind="tertiary"] span {
    color: #8B8A83 !important;
    -webkit-text-fill-color: #8B8A83 !important;
}
div[data-testid="stLayoutWrapper"]:has(.bf-card-marker) div[data-testid="stButton"] > button[kind="tertiary"]:hover {
    color: #1A1A18 !important;
    -webkit-text-fill-color: #1A1A18 !important;
    background: transparent !important;
}

.bf-empty {
    padding: 40px 0;
    text-align: center;
    color: #8B8A83;
    font-family: 'Inter', sans-serif;
    font-size: 13.5px;
}
</style>
"""


# ── Card rendering ───────────────────────────────────────────────────────────

def _render_card_header_html(card: Card, expanded: bool) -> str:
    needs_tag = (
        '<span class="bf-tag bf-tag--needs">NEEDS YOU</span>'
        if card.needs_you else ""
    )
    return (
        '<div class="bf-card-top">'
        '<div class="bf-tagrow">'
        f'<span class="bf-tag">{card.type}</span>'
        f'{needs_tag}'
        f'<span class="bf-context">{card.context}</span>'
        '</div>'
        f'<span class="bf-elapsed">{card.elapsed}</span>'
        '</div>'
    )


def _render_action_buttons(card: Card) -> None:
    """Three Streamlit buttons inside the card. Visual only — increments
    sidebar counters and removes the card from the active list."""
    primary_col, edit_col, skip_col = st.columns([2, 1, 1.4])
    with primary_col:
        if st.button(card.primary_action, key=f"prim_{card.id}",
                     use_container_width=True, type="primary"):
            _handle_send(card)
    with edit_col:
        if st.button("Edit", key=f"edit_{card.id}", use_container_width=True):
            st.session_state["expanded_card"] = card.id
            st.session_state[f"editing_{card.id}"] = True
            st.rerun()
    with skip_col:
        if st.button(card.skip_label, key=f"skip_{card.id}",
                     use_container_width=True, type="tertiary"):
            _handle_skip(card)


def _handle_send(card: Card) -> None:
    sent = st.session_state.setdefault("queue_sent_ids", set())
    sent.add(card.id)
    st.session_state["queue_sent_count"] = len(sent)
    st.session_state["expanded_card"] = None
    st.session_state.pop(f"editing_{card.id}", None)
    st.toast(f"Sent · {card.context}")
    st.rerun()


def _handle_skip(card: Card) -> None:
    skipped = st.session_state.setdefault("queue_skipped_ids", set())
    skipped.add(card.id)
    st.session_state["queue_skipped_count"] = len(skipped)
    st.session_state["expanded_card"] = None
    st.session_state.pop(f"editing_{card.id}", None)
    st.toast(f"Skipped · {card.context}")
    st.rerun()


def _handle_edit(card: Card) -> None:
    """Enter edit mode — swaps the static drafted-reply HTML for a
    Streamlit textarea on the next render."""
    print(f"[edit] start for {card.id}")
    st.session_state[f"editing_{card.id}"] = True
    st.rerun()


def _handle_save_edit(card: Card) -> None:
    """Persist the textarea value (already in session_state via
    widget binding) and exit edit mode."""
    print(f"[edit] save for {card.id}")
    st.session_state[f"editing_{card.id}"] = False
    st.toast(f"Saved · {card.context}")
    st.rerun()


def _handle_cancel_edit(card: Card) -> None:
    """Discard pending edits and revert the body to the original
    drafted_body. Removing the session_state key unbinds the textarea
    value so the next render falls back to the seed text."""
    print(f"[edit] cancel for {card.id}")
    st.session_state[f"editing_{card.id}"] = False
    st.session_state.pop(f"draft_body_{card.id}", None)
    st.rerun()


def _build_extras_html(card: Card) -> str:
    """Build the FROM / DRAFTED / WHY / ATTACHMENTS HTML as a single
    string. Lives inside the <details> body so expansion is pure CSS."""
    avail_doc_types = {dt for dt, _ in card.docs}

    parts: list[str] = []

    # FROM block (only if email card)
    if card.from_email:
        parts.append(
            f'<div class="bf-block-h">FROM {card.from_email}</div>'
            f'<div class="bf-from">{_esc(card.from_body)}</div>'
        )

    # DRAFTED block — prefer the saved (edited) body from session_state
    # if the broker has edited this card; fall back to the seed body.
    current_body = st.session_state.get(
        f"draft_body_{card.id}", card.drafted_body,
    )
    body_with_links = _linkify_doc_refs(
        _esc(current_body), card.id, avail_doc_types,
    )
    parts.append(
        f'<div class="bf-block-h">{card.drafted_label} '
        f'&middot; TO {card.drafted_to}</div>'
        '<div class="bf-draft-wrap">'
        f'<div class="bf-draft-subject">Subject: {card.drafted_subject}</div>'
        f'<div class="bf-draft-body">{body_with_links}</div>'
        '</div>'
    )

    # WHY block
    why_label = (
        "WHY BROKERFLOW FLAGGED THIS"
        if card.type == "NEW BRAND"
        else "WHY BROKERFLOW DRAFTED THIS"
    )
    bullets_html = "".join(
        '<li>'
        f'<span class="bf-reason-text">{_esc(b.text)}</span>'
        + (f'<span class="bf-reason-src">&#8599; {b.source}</span>' if b.source else '')
        + '</li>'
        for b in card.reasoning
    )
    drafted_by = " &rarr; ".join(_AGENT_LABELS.get(a, a) for a in card.agent_origin)
    drafted_by_html = (
        f'<div class="bf-drafted-by">'
        f'Drafted by: <span class="bf-drafted-by-agent">{drafted_by}</span> '
        f'<span class="bf-drafted-by-time">&middot; {card.elapsed} ago</span>'
        f'</div>'
    ) if drafted_by else ""
    parts.append(
        f'<div class="bf-block-h">{why_label}</div>'
        f'{drafted_by_html}'
        f'<ul class="bf-reasoning">{bullets_html}</ul>'
    )

    # Attachments row — data-doc-id triggers the JS panel handler;
    # no Streamlit rerun on click.
    if card.docs:
        from agents._shared import doc_storage as _ds
        items_html = []
        for doc_type, label in card.docs:
            info = _ds.get(card.id, doc_type)
            meta = "PDF · — pages" if not info else (
                f"PDF · {info['pages']} page{'s' if info['pages'] != 1 else ''}"
            )
            doc_id = f"{card.id}:{doc_type}"
            items_html.append(
                f'<a class="bf-attach-item" href="#" data-doc-id="{doc_id}">'
                f'<span class="bf-attach-icon">&#128196;</span>'
                f'<span class="bf-attach-name">{label}</span>'
                f'<span class="bf-attach-meta">{meta}</span>'
                f'<span class="bf-attach-open">&#8599; Open</span>'
                f'</a>'
            )
        parts.append(
            '<div class="bf-attach-row">'
            '<div class="bf-attach-h">ATTACHMENTS</div>'
            + "".join(items_html) +
            '</div>'
        )

    return '<div class="bf-card-extras">' + "".join(parts) + '</div>'


def _render_card_unified(card: Card) -> None:
    """Single render for all cards.

    Two modes:
      - Normal: header + summary + <details> with FROM/DRAFTED/WHY/
        ATTACHMENTS. Expand is pure CSS (instant, no rerun).
      - Edit: header + summary + always-expanded extras with the
        drafted body replaced by a Streamlit st.text_area. Primary
        and Edit buttons swap to Save and Cancel.
    """
    is_editing = bool(st.session_state.get(f"editing_{card.id}", False))

    avail_doc_types = {dt for dt, _ in card.docs}
    summary_with_links = _linkify_doc_refs(
        _esc(card.summary_html), card.id, avail_doc_types,
    )

    # Always render a NEEDS YOU slot — visible if card.needs_you, else
    # invisible placeholder. Reserves layout space so the context text
    # starts at the same x-position on every card.
    needs_visibility_class = "" if card.needs_you else " bf-tag--needs-placeholder"
    needs_tag = (
        f'<span class="bf-tag bf-tag--needs{needs_visibility_class}">'
        'NEEDS YOU</span>'
    )
    header_left_html = (
        '<div class="bf-card-header-l">'
        f'<span class="bf-tag bf-tag--type">{card.type}</span>'
        f'{needs_tag}'
        f'<span class="bf-context">{card.context}</span>'
        '</div>'
    )
    elapsed_html = f'<span class="bf-elapsed">{card.elapsed}</span>'

    with st.container(border=True):
        st.markdown('<div class="bf-card-marker"></div>',
                    unsafe_allow_html=True)

        # Header row — left flexes, right column is sized by the
        # nested action row's fixed widths (CSS sets flex-basis).
        left_col, right_col = st.columns([3, 2])
        with left_col:
            st.markdown(header_left_html, unsafe_allow_html=True)
        with right_col:
            time_col, prim_col, edit_col, skip_col = st.columns(
                [0.48, 1.6, 0.8, 0.6]
            )
            with time_col:
                st.markdown(
                    f'<div class="bf-card-time-cell">{elapsed_html}</div>',
                    unsafe_allow_html=True,
                )
            if is_editing:
                with prim_col:
                    if st.button("Save", key=f"save_{card.id}",
                                 type="primary", use_container_width=True):
                        _handle_save_edit(card)
                with edit_col:
                    if st.button("Cancel", key=f"cancel_{card.id}",
                                 use_container_width=True):
                        _handle_cancel_edit(card)
                with skip_col:
                    if st.button(card.skip_label, key=f"skip_{card.id}",
                                 type="tertiary", use_container_width=True):
                        _handle_skip(card)
            else:
                with prim_col:
                    if st.button(card.primary_action, key=f"prim_{card.id}",
                                 type="primary", use_container_width=True):
                        _handle_send(card)
                with edit_col:
                    if st.button("Edit", key=f"edit_{card.id}",
                                 use_container_width=True):
                        _handle_edit(card)
                with skip_col:
                    if st.button(card.skip_label, key=f"skip_{card.id}",
                                 type="tertiary", use_container_width=True):
                        _handle_skip(card)

        if is_editing:
            _render_card_edit_mode(card, summary_with_links)
        else:
            # Summary + collapsible extras. data-card-id lets the
            # restore-open-state script remember which cards the user
            # had expanded across Streamlit reruns.
            st.markdown(
                f'<details class="bf-card-details" data-card-id="{card.id}">'
                '<summary class="bf-card-summary-row">'
                f'<div class="bf-card-summary">{summary_with_links}</div>'
                '<span class="bf-show-reasoning">'
                'Show reasoning <span class="bf-chevron">&darr;</span>'
                '</span>'
                '</summary>'
                + _build_extras_html(card)
                + '</details>',
                unsafe_allow_html=True,
            )


def _render_card_edit_mode(card: Card, summary_with_links: str) -> None:
    """Always-expanded edit view: same blocks as the static expanded
    view, but the drafted body is a Streamlit text_area so the broker
    can rewrite it. Subject stays read-only above the textarea."""
    avail_doc_types = {dt for dt, _ in card.docs}

    # Summary (with the same active-card blue accent border as <details>[open])
    st.markdown(
        '<div class="bf-card-extras bf-card-edit-mode">'
        f'<div class="bf-card-summary bf-card-summary--editing">'
        f'{summary_with_links}</div>',
        unsafe_allow_html=True,
    )

    # FROM block (only if email card)
    if card.from_email:
        st.markdown(
            f'<div class="bf-block-h">FROM {card.from_email}</div>'
            f'<div class="bf-from">{_esc(card.from_body)}</div>',
            unsafe_allow_html=True,
        )

    # DRAFTED block header + read-only subject
    st.markdown(
        f'<div class="bf-block-h">{card.drafted_label} '
        f'&middot; TO {card.drafted_to}</div>'
        '<div class="bf-edit-subject">'
        f'<span class="bf-edit-subject-label">Subject</span>'
        f'<span class="bf-edit-subject-value">{card.drafted_subject}</span>'
        '</div>',
        unsafe_allow_html=True,
    )

    # Editable body — Streamlit widget, value persists across reruns
    # via the session_state key.
    current_body = st.session_state.get(
        f"draft_body_{card.id}", card.drafted_body,
    )
    st.text_area(
        "Edit drafted body",
        value=current_body,
        key=f"draft_body_{card.id}",
        height=320,
        label_visibility="collapsed",
    )

    # WHY block (same as normal mode)
    why_label = (
        "WHY BROKERFLOW FLAGGED THIS"
        if card.type == "NEW BRAND"
        else "WHY BROKERFLOW DRAFTED THIS"
    )
    bullets_html = "".join(
        '<li>'
        f'<span class="bf-reason-text">{_esc(b.text)}</span>'
        + (f'<span class="bf-reason-src">&#8599; {b.source}</span>'
           if b.source else '')
        + '</li>'
        for b in card.reasoning
    )
    drafted_by = " &rarr; ".join(
        _AGENT_LABELS.get(a, a) for a in card.agent_origin
    )
    drafted_by_html = (
        f'<div class="bf-drafted-by">'
        f'Drafted by: <span class="bf-drafted-by-agent">{drafted_by}</span> '
        f'<span class="bf-drafted-by-time">&middot; {card.elapsed} ago</span>'
        f'</div>'
    ) if drafted_by else ""

    parts = [
        f'<div class="bf-block-h">{why_label}</div>'
        f'{drafted_by_html}'
        f'<ul class="bf-reasoning">{bullets_html}</ul>'
    ]

    # Attachments row
    if card.docs:
        from agents._shared import doc_storage as _ds
        items_html = []
        for doc_type, label in card.docs:
            info = _ds.get(card.id, doc_type)
            meta = "PDF · — pages" if not info else (
                f"PDF · {info['pages']} page"
                f"{'s' if info['pages'] != 1 else ''}"
            )
            doc_id = f"{card.id}:{doc_type}"
            items_html.append(
                f'<a class="bf-attach-item" href="#" '
                f'data-doc-id="{doc_id}">'
                f'<span class="bf-attach-icon">&#128196;</span>'
                f'<span class="bf-attach-name">{label}</span>'
                f'<span class="bf-attach-meta">{meta}</span>'
                f'<span class="bf-attach-open">&#8599; Open</span>'
                f'</a>'
            )
        parts.append(
            '<div class="bf-attach-row">'
            '<div class="bf-attach-h">ATTACHMENTS</div>'
            + "".join(items_html) +
            '</div>'
        )

    parts.append('</div>')  # close bf-card-extras
    st.markdown("".join(parts), unsafe_allow_html=True)


def _preserve_filter_query() -> str:
    """Append &filter=...&brand=... to URL anchors so card click doesn't lose
    the active filter."""
    out = ""
    f = st.session_state.get("queue_filter")
    b = st.session_state.get("queue_brand")
    if f and f != "today":
        out += f"&filter={f}"
    if b:
        out += f"&brand={b}"
    return out


# ── Public render entry point ────────────────────────────────────────────────

def consume_expand_query() -> bool:
    """No-op shim — broker_shell.consume_nav_query_param() now handles
    both ?nav= and ?expand= in a single pass."""
    return False


def render_queue_topbar(crumb_parts: list[tuple[str, bool]]) -> None:
    """Combined topbar: breadcrumb LEFT, ask bar RIGHT, single row.

    Called by render_shell as the queue's custom_topbar slot. The marker
    div scopes the column-row CSS so it doesn't leak to other pages.

    The ask bar is wrapped in st.form(clear_on_submit=True) so the
    text_input clears automatically after each submit — without the
    form, Streamlit retains widget state across reruns and second
    submissions get garbled."""
    from ui.broker_shell import render_crumb_html

    cols = st.columns([1.6, 1])
    with cols[0]:
        st.markdown(
            '<div class="bf-queue-topbar-marker"></div>'
            + render_crumb_html(crumb_parts),
            unsafe_allow_html=True,
        )
    with cols[1]:
        with st.form("bf_ask_topbar_form", clear_on_submit=True,
                     border=False):
            query = st.text_input(
                "Ask BrokerFlow",
                placeholder="Ask BrokerFlow anything…",
                key="bf_ask_input",
                label_visibility="collapsed",
            )
            submitted = st.form_submit_button("Send", type="primary")
            if submitted and query.strip():
                _open_chat_with_query(query.strip())


# ── Slide-up chat panel ──────────────────────────────────────────────────────

def _render_chat_panel() -> None:
    """Fixed-bottom slide-up chat panel. Renders only when chat_open=True.

    Conversation lives in st.session_state.ask_conversation as a list of
    {"role": "user"|"assistant", "content": str}. Streaming uses an
    st.empty() placeholder updated per token."""
    history: list[dict] = st.session_state.setdefault("ask_conversation", [])
    pending = st.session_state.pop("chat_pending_query", None)

    # Dim backdrop behind the panel — clicking anywhere on it closes
    # the chat. The backdrop sits between the queue (z=auto) and the
    # panel (z=200) at z=190, so it dims the queue but not the panel.
    close_href = (
        f"?nav=queue{_preserve_filter_query()}&chat_close=1"
    )
    st.markdown(
        f'<a href="{close_href}" target="_self" '
        'style="text-decoration:none;">'
        '<div class="bf-chat-backdrop"></div></a>',
        unsafe_allow_html=True,
    )

    with st.container():
        st.markdown(
            '<div class="bf-chat-marker"></div>'
            '<div class="bf-chat-head">'
            '<div class="bf-chat-head-l">'
            f'<a class="bf-chat-newchat" href="?nav=queue'
            f'{_preserve_filter_query()}&chat_clear=1" target="_self">'
            '<span class="bf-chat-newchat-plus">+</span> Ask BrokerFlow'
            '</a>'
            '</div>'
            f'<a class="bf-chat-close" href="?nav=queue'
            f'{_preserve_filter_query()}&chat_close=1" target="_self">&times;</a>'
            '</div>'
            '<div class="bf-chat-sub">I see all your brands, accruals, '
            'POs, demos, and email history.</div>',
            unsafe_allow_html=True,
        )

        # Scrollable conversation area — nested st.container so we get a
        # real DOM wrapper for flex:1 + overflow-y:auto via :has() scoping.
        with st.container():
            st.markdown(
                '<div class="bf-chat-msgs-marker"></div>',
                unsafe_allow_html=True,
            )

            # Render frozen conversation history
            for msg in history:
                _render_msg(msg["role"], msg["content"])

            # If a query is pending: render user bubble + start streaming
            if pending:
                history.append({"role": "user", "content": pending})
                _render_msg("user", pending)

                placeholder = st.empty()
                full = ""
                try:
                    from agents.ask_brokerflow import stream_ask
                    prior = history[:-1]
                    for tok in stream_ask(pending, prior):
                        full += tok
                        placeholder.markdown(
                            '<div class="bf-chat-msg-assistant">'
                            + _md_to_html(full) +
                            '<span class="bf-chat-cursor"></span></div>',
                            unsafe_allow_html=True,
                        )
                except Exception as exc:  # noqa: BLE001
                    print(f"[chat_panel] stream failed: "
                          f"{type(exc).__name__}: {str(exc)[:200]}")
                    full = full or (
                        "BrokerFlow is taking longer than usual. "
                        "Try rephrasing or ask again."
                    )

                placeholder.markdown(
                    '<div class="bf-chat-msg-assistant">'
                    + _md_to_html(full) +
                    '</div>',
                    unsafe_allow_html=True,
                )
                history.append({"role": "assistant", "content": full})

        # Auto-scroll-to-bottom: install a one-time MutationObserver on
        # the messages container in the parent document. Sticks to the
        # bottom unless the user manually scrolls up >80px.
        _inject_chat_autoscroll()

        # Esc key closes the chat panel
        _inject_chat_esc_close()

    # Footer input — st.form(clear_on_submit=True) so the input clears
    # on every Send. Without the form, Streamlit retains the previous
    # value and the second message gets dropped or garbled.
    with st.container():
        st.markdown('<div class="bf-chat-input-marker"></div>',
                    unsafe_allow_html=True)
        with st.form("bf_chat_followup_form", clear_on_submit=True,
                     border=False):
            followup = st.text_input(
                "Follow-up",
                placeholder="Ask anything…",
                key="bf_chat_followup",
                label_visibility="collapsed",
            )
            submitted = st.form_submit_button("Send", type="primary")
            if submitted and followup.strip():
                _submit_chat_query(followup.strip())


def _inject_doc_panel_handler() -> None:
    """Bind click handlers for opening / closing the doc side panel
    purely client-side. No Streamlit rerun → instant open/close.

    Triggers (anywhere in the parent doc):
      - .bf-attach-item[data-doc-id]   → open matching panel
      - .bf-doc-link[data-doc-id]      → open matching panel
      - .bf-doc-close-btn              → close panel
      - click on .bf-doc-overlay-html  → close panel
      - Esc key                        → close panel
    """
    import streamlit.components.v1 as components
    components.html(
        """
        <script>
        (function () {
            const doc = window.parent.document;
            if (doc.body.dataset.bfDocPanelHandler === '1') return;
            doc.body.dataset.bfDocPanelHandler = '1';

            function openPanel(docId) {
                doc.querySelectorAll('.bf-doc-panel-html').forEach(p => {
                    p.classList.remove('open');
                });
                const panel = doc.querySelector(
                    '.bf-doc-panel-html[data-doc-id="' + docId + '"]'
                );
                if (!panel) return;
                panel.classList.add('open');
                const overlay = doc.querySelector('.bf-doc-overlay-html');
                if (overlay) overlay.classList.add('open');
                doc.body.style.overflow = 'hidden';
            }
            function closePanel() {
                doc.querySelectorAll('.bf-doc-panel-html').forEach(p => {
                    p.classList.remove('open');
                });
                const overlay = doc.querySelector('.bf-doc-overlay-html');
                if (overlay) overlay.classList.remove('open');
                doc.body.style.overflow = '';
            }

            doc.addEventListener('click', (e) => {
                const trigger = e.target.closest('[data-doc-id]');
                if (trigger && (
                    trigger.classList.contains('bf-attach-item') ||
                    trigger.classList.contains('bf-doc-link')
                )) {
                    e.preventDefault();
                    openPanel(trigger.dataset.docId);
                    return;
                }
                if (e.target.closest('.bf-doc-close-btn')) {
                    e.preventDefault();
                    closePanel();
                    return;
                }
                if (e.target.closest('.bf-doc-overlay-html')) {
                    e.preventDefault();
                    closePanel();
                }
            }, true);

            doc.addEventListener('keydown', (e) => {
                if (e.key === 'Escape') closePanel();
            });
        })();
        </script>
        """,
        height=0,
    )


def _start_seed_pdfs_background() -> None:
    """Generate the seed PDFs in a background thread on first queue
    render. Doesn't block the UI; PDFs are usually ready by the time
    the broker actually clicks "Open as PDF" on a side panel."""
    if st.session_state.get("_seed_pdfs_bg_started"):
        return
    st.session_state["_seed_pdfs_bg_started"] = True

    import threading

    def _gen():
        try:
            from agents._shared import doc_storage, document_data
            for card_id, doc_type, agent, payload in (
                document_data.all_seed_entries()
            ):
                try:
                    doc_storage.ensure_pdf(card_id, agent, doc_type, payload)
                except Exception as exc:  # noqa: BLE001
                    print(f"[seed_pdfs_bg] {card_id}/{doc_type} failed: "
                          f"{type(exc).__name__}: {exc}")
            print("[seed_pdfs_bg] all seed PDFs generated")
        except Exception as exc:  # noqa: BLE001
            print(f"[seed_pdfs_bg] aborted: {type(exc).__name__}: {exc}")


def _start_chat_context_warmup() -> None:
    """Warm the Ask BrokerFlow context cache on first queue render so
    the broker's first chat query doesn't pay the ~500ms Supabase
    fetch cost. Runs in a daemon thread; fire-and-forget."""
    if st.session_state.get("_ctx_warmup_started"):
        return
    st.session_state["_ctx_warmup_started"] = True

    import threading

    def _warmup():
        try:
            from agents.ask_brokerflow.context_builder import build_context
            build_context()
            print("[ctx_warmup] context cache warmed")
        except Exception as exc:  # noqa: BLE001
            print(f"[ctx_warmup] {type(exc).__name__}: {exc}")

    threading.Thread(target=_warmup, daemon=True).start()


def _inject_card_expand_persistence() -> None:
    """Persist each card's <details> open state across Streamlit reruns.

    Native HTML <details> handles expand/collapse instantly with no
    Streamlit rerun. But when the user clicks a Streamlit button
    (Send / Skip / Edit), Streamlit reruns and emits fresh HTML —
    which defaults all <details> to closed. This script syncs each
    card's open state to localStorage on toggle and restores it on
    every render so card state survives reruns.

    On a "fresh entry" (after navigating from landing), the persistence
    is wiped so the broker doesn't see a card pre-expanded from a
    previous session. queue_fresh_entry is set to True by the goto=app
    and goto=landing handlers and consumed here."""
    import streamlit.components.v1 as components
    fresh_entry = bool(st.session_state.pop("queue_fresh_entry", False))
    fresh_js = "true" if fresh_entry else "false"
    components.html(
        """
        <script>
        (function () {
            const FRESH = """ + fresh_js + """;
            const doc = window.parent.document;
            const cards = doc.querySelectorAll(
                '.bf-card-details[data-card-id]'
            );
            if (!cards.length) return;

            // On fresh queue entry, wipe ALL bf-card-open-* entries
            // so the user doesn't see a card pre-expanded from a
            // previous browser session.
            if (FRESH) {
                for (let i = localStorage.length - 1; i >= 0; i--) {
                    const key = localStorage.key(i);
                    if (key && key.startsWith('bf-card-open-')) {
                        localStorage.removeItem(key);
                    }
                }
            } else {
                // Otherwise just clean up entries for cards that are
                // no longer visible (sent/skipped).
                const visibleIds = new Set(
                    Array.from(cards).map(c => c.dataset.cardId)
                );
                for (let i = localStorage.length - 1; i >= 0; i--) {
                    const key = localStorage.key(i);
                    if (key && key.startsWith('bf-card-open-')) {
                        const cid = key.slice('bf-card-open-'.length);
                        if (!visibleIds.has(cid)) {
                            localStorage.removeItem(key);
                        }
                    }
                }
            }

            cards.forEach(card => {
                const id = card.dataset.cardId;
                const key = `bf-card-open-${id}`;
                if (localStorage.getItem(key) === '1') {
                    card.open = true;
                }
                if (!card.dataset.bfToggleBound) {
                    card.dataset.bfToggleBound = '1';
                    card.addEventListener('toggle', () => {
                        if (card.open) {
                            localStorage.setItem(key, '1');
                        } else {
                            localStorage.removeItem(key);
                        }
                    });
                }
            });
        })();
        </script>
        """,
        height=0,
    )


def _inject_chat_esc_close() -> None:
    """Bind Esc-to-close for the chat panel. The close ✕ and the dim
    backdrop (anchor wrapping a div) both already use URL navigation;
    this adds keyboard parity."""
    import streamlit.components.v1 as components
    components.html(
        """
        <script>
        (function () {
            const doc = window.parent.document;
            if (doc.body.dataset.bfChatEscBound === '1') return;
            doc.body.dataset.bfChatEscBound = '1';
            doc.addEventListener('keydown', (e) => {
                if (e.key !== 'Escape') return;
                // Only close if the chat panel is actually rendered
                const panel = doc.querySelector('.bf-chat-marker');
                if (!panel) return;
                // Trigger the same URL-based close as the ✕ button
                const closer = doc.querySelector('.bf-chat-close');
                if (closer) closer.click();
            });
        })();
        </script>
        """,
        height=0,
    )


def _inject_chat_autoscroll() -> None:
    """Pin the chat scroll area to the bottom as new content arrives.

    Uses an iframe-isolated script (st.components.v1.html) that reaches
    into the parent document. A MutationObserver watches the messages
    container; on every mutation, it scrolls to bottom — unless the
    user has manually scrolled up more than 80px from the bottom, in
    which case it leaves them alone.

    Re-rendered every chat panel pass; the script's data-attribute
    guard prevents binding more than one observer."""
    import streamlit.components.v1 as components
    components.html(
        """
        <script>
        (function () {
            const doc = window.parent.document;
            // Find the scroll container in the parent app
            const marker = doc.querySelector('.bf-chat-msgs-marker');
            if (!marker) return;
            const scroller = marker.closest(
                'div[data-testid="stLayoutWrapper"]'
            );
            if (!scroller) return;

            // Don't re-bind if we've already attached an observer
            if (scroller.dataset.bfAutoscrollBound === '1') {
                // Still nudge scroll to bottom on this fresh render
                if (!scroller.dataset.bfUserScrolled) {
                    scroller.scrollTop = scroller.scrollHeight;
                }
                return;
            }
            scroller.dataset.bfAutoscrollBound = '1';

            // Initial scroll
            scroller.scrollTop = scroller.scrollHeight;

            // Track user scroll intent — if they scroll up more than
            // 80px from the bottom, stop auto-scrolling. If they
            // scroll back to within 40px, resume.
            scroller.addEventListener('scroll', () => {
                const fromBottom = scroller.scrollHeight
                                 - scroller.scrollTop
                                 - scroller.clientHeight;
                if (fromBottom > 80) {
                    scroller.dataset.bfUserScrolled = '1';
                } else if (fromBottom < 40) {
                    delete scroller.dataset.bfUserScrolled;
                }
            }, { passive: true });

            // Pin to bottom on every content mutation, unless user
            // is reading further up.
            const obs = new MutationObserver(() => {
                if (!scroller.dataset.bfUserScrolled) {
                    scroller.scrollTop = scroller.scrollHeight;
                }
            });
            obs.observe(scroller, {
                childList: true,
                subtree: true,
                characterData: true,
            });
        })();
        </script>
        """,
        height=0,
    )


def _open_chat_with_query(query: str) -> None:
    """Open the chat panel and queue `query` as the first user message.

    No st.rerun() here — the form submit that called this is already
    triggering a rerun. The current run continues to render_queue_view's
    body, which renders the chat panel since chat_open is True. Saves
    one full queue re-render per submit (~150-300ms)."""
    print(f"[chat] open_chat_with_query: {query!r}")
    st.session_state["chat_open"] = True
    st.session_state["chat_pending_query"] = query


def _submit_chat_query(query: str) -> None:
    """Submit a follow-up inside an already-open chat panel.

    Needs st.rerun() — unlike _open_chat_with_query, the followup
    form lives INSIDE the panel which has already rendered its
    messages. We need a rerun to re-render the panel with the new
    pending query."""
    history_len = len(st.session_state.get("ask_conversation", []))
    print(f"[chat] submit_chat_query: {query!r} (history len before: {history_len})")
    st.session_state["chat_pending_query"] = query
    st.rerun()


def _render_msg(role: str, content: str) -> None:
    if role == "user":
        st.markdown(
            f'<div class="bf-chat-msg-user">{_esc(content)}</div>',
            unsafe_allow_html=True,
        )
    else:
        st.markdown(
            f'<div class="bf-chat-msg-assistant">{_md_to_html(content)}</div>',
            unsafe_allow_html=True,
        )


def _md_to_html(md: str) -> str:
    """Light markdown → HTML for streaming responses. Handles bold, lists,
    paragraphs. Stays simple to avoid pulling a heavy markdown dep."""
    if not md:
        return ""
    text = _esc(md)

    # **bold** → <strong>
    import re
    text = re.sub(r"\*\*([^*]+)\*\*", r"<strong>\1</strong>", text)
    # _italic_ or *italic* → <em>  (single-char, not greedy)
    text = re.sub(r"(?<!\*)\*([^*\n]+)\*(?!\*)", r"<em>\1</em>", text)

    # Convert bullet lists block-by-block
    out_lines: list[str] = []
    in_ul = False
    for line in text.split("\n"):
        bullet = re.match(r"^\s*[-•]\s+(.*)", line)
        numbered = re.match(r"^\s*\d+[\.\)]\s+(.*)", line)
        if bullet or numbered:
            if not in_ul:
                out_lines.append("<ul>")
                in_ul = True
            item = (bullet or numbered).group(1)
            out_lines.append(f"<li>{item}</li>")
        else:
            if in_ul:
                out_lines.append("</ul>")
                in_ul = False
            out_lines.append(line)
    if in_ul:
        out_lines.append("</ul>")

    # Paragraphs from blank-line separated blocks. Collapse runs of 2+
    # blank lines so excess whitespace from the LLM doesn't yield empty
    # <p> tags (which used to inflate vertical spacing).
    joined = re.sub(r"\n{2,}", "\n\n", "\n".join(out_lines))
    blocks = joined.split("\n\n")
    html_blocks = []
    for b in blocks:
        b = b.strip()
        if not b:
            continue
        if b.startswith("<ul>") or b.startswith("<ol>") or b.startswith("<li>"):
            html_blocks.append(b)
        else:
            html_blocks.append("<p>" + b.replace("\n", "<br>") + "</p>")
    return "".join(html_blocks)


def render_queue_view() -> None:
    st.markdown(_QUEUE_CSS, unsafe_allow_html=True)

    # Background-thread the seed PDF generation. The in-app preview
    # reads from the payload dict directly (no PDF needed to display
    # the side panel), so this is fire-and-forget. PDFs are usually
    # ready within ~300ms — long before the broker clicks "Open as
    # PDF" or "Download" inside a panel.
    _start_seed_pdfs_background()

    # Warm the chat context cache in a background thread so the
    # broker's first Ask BrokerFlow query doesn't pay the cold-cache
    # ~500ms Supabase fetch latency. Idempotent.
    _start_chat_context_warmup()

    # All ?nav=, ?open_doc=, ?close_doc=, ?chat_*= query params are
    # handled by broker_shell.consume_nav_query_param() in one pass
    # before render_queue_view() runs.

    filter_key = st.session_state.get("queue_filter", "today")
    brand = st.session_state.get("queue_brand")
    cards = _filter_cards(filter_key, brand)

    label = _filter_label(filter_key, brand)
    count_word = "card" if len(cards) == 1 else "cards"

    # Section subheader (small, matches filter pills weight) + pills
    pills = []
    for key, lbl, _ in [
        ("today",     "ALL",                 len(_filter_cards("today", brand))),
        ("needs_you", f"NEEDS YOU · {len(_filter_cards('needs_you', brand))}", None),
        ("drafted",   f"DRAFTED · {len(_filter_cards('drafted', brand))}",     None),
    ]:
        active = (filter_key == key) or (filter_key not in ("today", "needs_you", "drafted") and key == "today")
        cls = "bf-queue-pill bf-queue-pill--active" if active else "bf-queue-pill"
        href = f"?nav=queue&filter={key}" + (f"&brand={brand}" if brand else "")
        pills.append(f'<a class="{cls}" href="{href}" target="_self">{lbl}</a>')
    pills_html = '<div class="bf-queue-pills">' + "".join(pills) + '</div>'

    st.markdown(
        '<div class="bf-queue-section-row">'
        f'<div class="bf-queue-h">{label} '
        f'<span class="bf-queue-h-count">&middot; {len(cards)} {count_word}</span></div>'
        f'{pills_html}'
        '</div>',
        unsafe_allow_html=True,
    )

    if not cards:
        st.markdown(
            '<div class="bf-empty">Nothing here yet — check back soon.</div>',
            unsafe_allow_html=True,
        )
        return

    # Single render path — extras live inside <details> so expand is
    # pure CSS (no Streamlit rerun, instant). See _render_card_unified.
    for card in cards:
        _render_card_unified(card)

    # Persist <details> open state across Streamlit reruns. Without
    # this, clicking any st.button (Send/Skip/Edit) reruns the script
    # and re-emits fresh HTML — losing the user's expanded card. The
    # script syncs open state to localStorage on toggle and restores
    # it on every render.
    _inject_card_expand_persistence()

    # Chat panel renders so it overlays the queue
    if st.session_state.get("chat_open"):
        _render_chat_panel()

    # All doc panels are pre-rendered as hidden HTML; JS toggles
    # which one is visible. Open/close is instant — no Streamlit
    # rerun, no re-render of the queue.
    _render_all_doc_panels()
    _inject_doc_panel_handler()
